### ISSUE TITLE
FeatureServer does not allow output geojson

### ISSUE THREAD

**Issue by brettmeyerowitz** [koopjs/koop#1041]
Hi,

The FeatureServer is incorrectly validating the formatSchema and not including geojson as a valid output. Can this be added in please?

e.g. http://[localhost:8080/file-geojson/rest/services/line/FeatureServer/0/query?f=geojson](http://localhost:8080/file-geojson/rest/services/line/FeatureServer/0/query?f=geojson) should return the geojson.

**Comment by rgwozdz** [comment]
fixed in [@koopjs/koop-core@10.4.15](https://github.com/koopjs/koop/releases/tag/%40koopjs%2Fkoop-core%4010.4.15)
