### ISSUE TITLE
adjust FeatureServer route urls

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop#112]
_From @jgravois on November 11, 2014 20:57_

_From @jgravois on November 11, 2014 18:17_

my recommendation is that FeatureServer urls adhere to the following convention:
http://koop.dc.esri.com/<b>rest/services</b>/github/chelm/grunt-geo/forks/FeatureServer/0

koop itself should return a valid ArcGIS Server like response for GETs/POSTs to
http://koop.dc.esri.com/rest/info
and
http://koop.dc.esri.com/rest/services (listing providers)

_Copied from original issue: chelm/koop-github#7_

_Copied from original issue: Esri/koop-server#35_

**Comment by ngoldman** [comment]
I disagree wholeheartedly. I don't think we should add ArcGIS Server conventions to the root of all URLs. They're bad conventions carried over from SOAP that don't belong in a modern web server. We've talked about working on expanding the `status` and `providers` routes that already exist on `koop.dc.esri.com` at http://koop.dc.esri.com/providers and http://koop.dc.esri.com/status respectively. I think finding a good forward-thinking convention to address the needs these cases represent would be the way to go.

**Comment by ngoldman** [comment]
Additionally, Koop can (and should) be mounted on a specific route as Express middleware like so:

```js
var app = require('express')()
var koop = require('koop)()
app.use('/koop', koop)
```

Exposing it like so would allow for the base route (http://koop.dc.esri.com/) to expose this kind of information by default rather than just returning an outdated demo page or a 404, and for koop itself to act more like API middleware within an express server.

**Comment by ajturner** [comment]
Agreed so long as Koop can quack like a FeatureService when existing apps come calling. It's not always clear which FS endpoints are doc'd, expected, or actually required. 

But there isn't a good reason to make it look like a duck merely for form's sake.

**Comment by ngoldman** [comment]
To my understanding we only really need to emulate the `FeatureServer` endpoint and everything to the right of it (`/0`, queries, etc).

@jgravois is there a reason to have these endpoints other than emulating ArcGIS Server (i.e. a use case that not having such endpoints blocks or impairs)?

**Comment by jgravois** [comment]
this suggestion was made in an attempt to get koop feature services to be valid AGOL gp input.  see comment [here](https://github.com/koopjs/koop/issues/95#issuecomment-61743734).

i've heard we've made significant progress in that area, so i'm going to close.
