### ISSUE TITLE
Explore refactoring file access with a pure s3 backed file system

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#119]
It'd be nice to use https://github.com/danilop/yas3fs to have more connected filesystem across instances. This will be crucial if we move towards koop itself never processing any downloads. If we rely on workers to generate files (on many servers) then we need to have the koop installs checking for files in one place. currently they will re-create a file that may exist on another koop filesystem. 

(even though they do check s3 so maybe its not big deal - this would be cleaner)

**Comment by dmfenton** [comment]
Koop has an S3 file system that works well
