### ISSUE TITLE
update esri-leaflet

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop#124]
Noticed esri-leaflet is quite out of date:

```js
/*! Esri-Leaflet - v0.0.1-beta.4 - 2014-03-09
```
> https://github.com/Esri/koop/blob/master/public/js/esri-leaflet.js#L1

Will open a PR to bump to latest (currently `1.0.0-rc.6`) when I get a chance.

**Comment by chelm** [comment]
:zap:

**Comment by ngoldman** [comment]
@jgravois wondering if you have an opinion on the best way to do this -- would be nice to use the CDN via

```
<script src="http://cdn-geoweb.s3.amazonaws.com/esri-leaflet/1.0.0-rc.6/esri-leaflet.js"></script>
```

rather than committing esri-leaflet's minified source to koop. @chelm what part of koop handles `public` getting served?

**Comment by jgravois** [comment]
i agree. CDN seems like the simplest, least maintenance way to go.

**Comment by chelm** [comment]
I actually think that the esri-leaflet in the code base is not being used. Each provider that supports a "preview" endpoint should be using the CDN (and be kept up-to-date in those repos). Unless we want to refactor the way the demo views in the providers work to include the libs in a more central way.

**Comment by chelm** [comment]
koop-socrata example: https://github.com/koopjs/koop-socrata/blob/master/views/demo.ejs#L54

**Comment by chelm** [comment]
So I'll verify that we can just blow away the checked in esri-leaflet code today.

**Comment by ngoldman** [comment]
@chelm makes sense to me. we probably don't need a `public` folder at all then, right?

**Comment by chelm** [comment]
@ngoldman I have removed the local esri-leaflet code, but we still need the public dir for `public/js/map.js` which is the shared logic for providers that have a preview method. This could change easily and we could say its up the to providers to be completely self-sustaining in they're support for things like views and maps and such. 

I think this is an artifact of the old way koop was built as one big piece. So we just need to make a decision and either leave it and doc that its there and how to use it, or blow it away and duplicate it in the providers that want it.

**Comment by ngoldman** [comment]
@chelm is this something that could act as a plugin?

**Comment by chelm** [comment]
@ngoldman good question. potentially yes but its a bit different. It could re-thought to be plugin I suppose. Let me ponder on that today.

**Comment by ngoldman** [comment]
Moving towards removing `preview` from Koop altogether (v3).

**Comment by ngoldman** [comment]
Esri-Leaflet needs to be updated in individual providers for now.
