### ISSUE TITLE
Move feature server code into its own node module

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#151]
Right now we have 3 files in `/lib` that handle everything to do with creating Feature Services: `lib/Query.js`, `lib/FeatureService.js`, and `lib/Extent.js` plus we also have some logic in the `lib/BaseController` that handles processing requests and passing them off to the correct FeatureService methods. 

I think we should extract the 3 FeatureService lib files into a new node module that is beyond just koop, and potentially include the logic in `lib/BaseController.js` in that module as well. This new module could be called something like `geojson-to-featureservice` or something and would just take a chunk geojson feature collection and return the correct response to a FeatureService query.

**Comment by ngoldman** [comment]
+1

I can try to tackle this next week. Currently wrapped up in another project.

**Comment by chelm** [comment]
@ngoldman otherprojects-- koop++

**Comment by ngoldman** [comment]
This was partially done in https://github.com/koopjs/koop-provider. The torch has been passed once more.
