### ISSUE TITLE
Return unique values of a field for filtering in ArcGIS Online

### ISSUE THREAD

**Issue by pholleran** [koopjs/koop#156]
Koop does not currently support the generateRenderer operation. As a result, when a koop-backed feature service is added to a webmap the unique value option for filtering cannot be used within the GUI.

ArcGIS Online's filter GUI calls the following to retrieve unique values and populate the drop-down:
```
<path>/featureserver/0/generateRenderer?classificationDef=%7B"type"%3A"uniqueValueDef"%2C"uniqueValueFields"%3A%5B"category"%5D%7D&f=json&callback=dojo.io.script.jsonp_dojoIoScript3._jsonpCallback
```
A workaround does exist for this, as the end-user can manually enter the desired value. This works fine for professionals who know the values within their data, but not so well for non-GIS pros.

**Comment by chelm** [comment]
This would be a cool thing to have.
