### ISSUE TITLE
Add HTML templating to json out put 

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#16]
This can be essentially copied from @nixta and his node ags stuff 

Each endpoint should follow the typically layout and structure of an AGS instance.

**Comment by ngoldman** [comment]
@dmfenton @nixta do you know or remember what this is about? should this still be a feature?

**Comment by dmfenton** [comment]
it shouldn't be part of the koop project

**Comment by ngoldman** [comment]
:+1:
