### ISSUE TITLE
For Consideration: Decimal Degree Precision

### ISSUE THREAD

**Issue by slibby** [koopjs/koop#162]
For geojson exports (and other formats) of large datasets, I think we may want to consider reducing decimal degree precision to reduce filesize. For complex polygon layers, the geometry section of the geojson file will take up the vast majority of the text space, and currently koop exports with 16-17 significant digits of precision:

`"geometry": { "type": "Polygon", "coordinates": [ [ [ 85.275995105195037, 27.708265241160536 ], [ 85.273401891751973, 27.704288656786961 ], [ 85.268215466662468, 27.704288656786961 ], [ 85.265622253219405, 27.708265241160536 ], [ 85.268215466662468, 27.712241680589148 ], [ 85.273401891751973, 27.712241680589148 ], [ 85.275995105195037, 27.708265241160536 ] ] ] } }`

 [Wikipedia shows us](http://en.wikipedia.org/wiki/Decimal_degrees) that 8 degrees of precision is down to 1mm of detail, which should be sufficient for most applications. Is it worth considering this when generating geojson, to save on disk and transfer overhead?

**Comment by slibby** [comment]
Though it would be great to get some "tectonic plate mapping" going!

**Comment by chelm** [comment]
@slibby I agree here. I think doing this on the front-end makes the most sense (before Koop caches the data). For koop-agol I was setting the precision to 6 on the request to the server and noticed some serious issues with very small scale data and that was removed in favor of taking whatever precision koop is given by a provider. 

If we were to enforce a koop precision of 8 i wonder what the best method for enforcing it at the DB level would be. ie is there an efficient or performance freindly way to reduce precision of coord pairs

**Comment by chelm** [comment]
@slibby Yup that makes sense. And actually for exports I can set `-lco COORDINATE_PRECISION=8` directly via ogr2ogr

**Comment by slibby** [comment]
@chelm coming back to this for a min - for geojson, need to rething a few things as it's stored in the DB right now, yes? But for CSV/Shapefile/KML exports you could add that coordinate call to the base models here, I think: https://github.com/Esri/koop/blob/master/lib/Exporter.js#L425

If that makes sense, I can try it out.

**Comment by chelm** [comment]
@slibby yes that'd be the spot

**Comment by dmfenton** [comment]
moved to https://github.com/FeatureServer/FeatureServer/issues/3
