### ISSUE TITLE
Add support for WFS output from any Koop provider

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop#163]
Support for OGC :balloon: 
- Initial support for GeoJSON and GML Simple Features

**Comment by DruidSmith** [comment]
This would be a huge benefit as there is currently a pretty big gap where it comes to WFS support in ArcGIS Online.  Koop could help bridge that gap.

**Comment by dmfenton** [comment]
I've started this with https://github.com/koopjs/koop-output-wfs

**Comment by rgwozdz** [comment]
@ajturner - checking on this as well as it's gone stale.  Is WFS support for all providers is still of interest?

**Comment by ajturner** [comment]
@rgwozdz yes, this is still of interest.

**Comment by rgwozdz** [comment]
https://github.com/koopjs/koop-output-wfs
