### ISSUE TITLE
Add support for WMS output from any Koop provider

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop#164]
Moar OGC

**Comment by calvinmetcalf** [comment]
I wrote an [express module](https://github.com/AppGeo/wms) for getting a wms/wmts service out of an xyz tile endpoint, probably wouldn't be able to use it directly but should help you avoid some pitfalls I ran into, most of the more gnarly bits of it are all things you'd be able to avoid by using mapnik directly.

**Comment by dmfenton** [comment]
very very cool, thanks @calvinmetcalf!

**Comment by rgwozdz** [comment]
@ajturner - just checking in on this.  It's been a little over three years since the issue was initially added.  Is WMS support for all providers is still of interest?

**Comment by ajturner** [comment]
Yes, this is still of interest @rgwozdz

**Comment by rgwozdz** [comment]
@ajturner this is now under development at https://github.com/koopjs/koop-output-wms
