### ISSUE TITLE
Custom styling / renderers

### ISSUE THREAD

**Issue by jseppi** [koopjs/koop#177]
Any plans for hooking up custom styling?

**Comment by chelm** [comment]
@jseppi Custom styling for FeatureServices or for things like images/tiles? I've done some toying with custom styling via the URL for tile generation but havent thought much about how to add styling into FeatureServices. 

Would love to get your opinion or thoughts on what you may need

**Comment by jseppi** [comment]
For FeatureServices. Looks like the renderers are hardcoded currently (https://github.com/Esri/koop/tree/master/templates/renderers). 
For GeoJSON based providers (my provider, and the Github and Gist providers) perhaps it could abide by [simplestyle spec](https://github.com/mapbox/simplestyle-spec) to derive the styles.

**Comment by chelm** [comment]
@jseppi yup I can get with that. I'm creating a koop roadmap doc right now and will add this feature to the planned next release.

**Comment by jseppi** [comment]
:+1:

**Comment by ngoldman** [comment]
@chelm cool! let me know how it goes with the roadmap. would be great to get that in https://github.com/koopjs/koopjs.github.io too :wink:

**Comment by chelm** [comment]
@ngoldman started the roadmap https://github.com/Esri/koop/blob/master/ROADMAP.md

Added this to v2.2.0 milestone

**Comment by dmfenton** [comment]
two years later we'll be picking this back up!

**Comment by chelm** [comment]
almost to the day :1st_place_medal:

**Comment by dmfenton** [comment]
Thanks to @tomtom92 Koop and Winnow now support running classifications and generating renderers through the Geoservices API. Please try it out!
