### ISSUE TITLE
Idea: desktop koop

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop#179]
Use [electron](https://github.com/atom/electron/blob/master/README.md) wraps Koop and allows user to enter external URL to view data.

**Comment by chelm** [comment]
Oh totally. Such fun to had with this one

**Comment by ngoldman** [comment]
I'd be interested in helping with this, I've done a couple things with electron :)

https://github.com/ngoldman/electron-hello-world
https://github.com/moose-team/friends

**Comment by ngoldman** [comment]
Starting point: https://github.com/koopjs/koop-ui
