### ISSUE TITLE
GeoJSON processing messages should be valid GeoJSON 

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop#180]
Because a non-GeoJSON (without features: []) may break simple clients

Also
https://twitter.com/cartocalypse/status/605074629712068608

**Comment by chelm** [comment]
@ajturner you mean when koop returns 202 on a `.geojson` mime you want "valid" geojson w/o the features array. That makes little sense to me. What makes valid geojson w/o an array of features. 

need some more info.

**Comment by ajturner** [comment]
Throw the status response at geojson.io - does it barf?
