### ISSUE TITLE
Add JSDocs to each file in lib/*

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#208]
Need to have docs for each method in each file

**Comment by ngoldman** [comment]
* [x] BaseController
* [ ] BaseModel
* [x] Cache
* [ ] ExportWorker
* [ ] Exporter
* [ ] FeatureServices
* [ ] Files
* [ ] GeoJSON
* [ ] Local
* [ ] Logger
* [ ] Query

**Comment by dmfenton** [comment]
This is done
