### ISSUE TITLE
Error: Errors need improvement

### ISSUE THREAD

**Issue by ungoldman** [koopjs/koop#209]
- Error handling needs to be improved
- Errors needs to be JS Error objects, not plain strings
- Error messages need to be improved (more informative)

See https://github.com/Esri/koop/commit/27b2c399412f24002c27974e6c684355794eff89#commitcomment-12313091 for an example and discussion of the problem.

**Comment by dmfenton** [comment]
This has been the pattern in Koop for a long time. You were such a great influence on Koop @ungoldman!

**Comment by ungoldman** [comment]
Thanks @dmfenton! 😅
