### ISSUE TITLE
Move to KoopJS org

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop#210]
All of Koop's modules now reside in the KoopJS org except for this one. It's confusing and unnecessary to manage Koop under the Esri github organization while managing its many submodules under the KoopJS org. We should move this repo to http://github.com/koopjs to make it easier for users to navigate related repositories and to make it easier to manage Koop and its submodules in the same place.

**Comment by chelm** [comment]
I hold the power to move this repo now. Pull the trigger now?

**Comment by ngoldman** [comment]
Do it!

**Comment by chelm** [comment]
:icecream: done :cherries:

**Comment by ajturner** [comment]
How about leaving a landing repo in the Esri org with a link to the new org?

**Comment by ngoldman** [comment]
@ajturner Github is currently redirecting https://github.com/Esri/koop to https://github.com/koopjs/koop.
