### ISSUE TITLE
Use CDN to host Leaflet images

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop#213]
We're using a CDN to serve Esri-Leaflet and I'm wondering if it's still necessary for us to host the icon images for Leaflet locally (https://github.com/koopjs/koop/tree/master/public/images).

A little investigation shows that the Leaflet CDN does not host them, but [cdnjs](https://cdnjs.com/) does (https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/images/layers.png). cdnjs also supports HTTPS, another thing missing from Leaflet CDN. I suggest we just switch over to cdnjs and remove the images folder as 0.7.3 is very stable and cdnjs isn't going anywhere. We'll need to make sure to point to the right image in any scripts like https://github.com/koopjs/koop/blob/master/public/js/map.js#L24.

**Comment by ngoldman** [comment]
Looks like I missed the images on Leaflet's CDN: http://cdn.leafletjs.com/leaflet-0.7.3/images/layers.png

The HTTPS support is a good reason to use CDNJS instead though. @patrickarlt any recommendations?

**Comment by ngoldman** [comment]
@patrickarlt says the stuff at https://github.com/koopjs/koop/blob/master/public/js/map.js#L21-L31 is the default anyway so we can strip that out and delete the images and Leaflet will just figure it out.

**Comment by patrickarlt** [comment]
@ngoldman is the JS built with something like browserify? If it is then leaflet wont be able to figure out where the images are hosted and you will need to do something like 

```js
L.Icon.Default.imagePath = 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/images';
```

to tell leaflet where the images are.

**Comment by ngoldman** [comment]
No browserify for now. Thanks for the heads up @patrickarlt
