### ISSUE TITLE
Logger is no longer parsing the log path correctly

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#218]
This line https://github.com/koopjs/koop/blob/master/lib/Logger.js#L11 has broke some of the provider tests. 

The issue (I'm suspecting) is that splice call is not returning what we think it should return.

**Comment by chelm** [comment]
cc @ngolgman

**Comment by chelm** [comment]
The previous version of the logger used this (ugly solution on purpose...) 

```
var logpath = config.logfile.split('/')
    logpath.splice(-1,1)
    logpath = logpath.join('/')
```

**Comment by chelm** [comment]
actually the correct thing to do is s/splice/slice/

**Comment by ngoldman** [comment]
Would probably be best to use something like https://nodejs.org/api/path.html#path_path_parse_pathstring rather than doing a lot of manual string manipulation to figure out the path

**Comment by chelm** [comment]
oh good call @ngoldman

**Comment by dmfenton** [comment]
psh fancy high-falutin stdlib

**Comment by ngoldman** [comment]
path.parse, path.format, and path.join are pretty handy for dealing with path stuff and they work cross-platform (linux, os x, win)
