### ISSUE TITLE
Service tables are not registered automatically

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop#233]
I'm not sure why I'm having this error while I'm trying to register a provider in a machine with Windows 8:

```bash
$ curl --data "host=https://data.lab.fiware.org&id=fiware" localhost:1337/ckan
{"name":"error","length":124,"severity":"ERROR","code":"42P01","position":"31","file":"src\\backend\\parser\\parse_relation.c","line":"986","routine":"parserOpenTable"}
```

I checked the [Postgres error codes](http://www.postgresql.org/docs/8.2/static/errcodes-appendix.html) and it means **UNDEFINED TABLE**

I have started the server in the same way as usual (in my machine with Windows 7):

```bash
C:\Workspace\koop-sample-app>node server.js
Express koop server listening on port 1337
info: CREATE TABLE "koopinfo" (id varchar(255) PRIMARY KEY, info JSON)
info: CREATE TABLE "kooptimers" (id varchar(255) PRIMARY KEY, expires varchar(25
))
```

I also SET the PYTHON variable and checked that Postgis in available in the database. Any clue about what can be happening?

Thanks!

**Comment by dmfenton** [comment]
Hi @hhkaos I've seen this before. There is an existing bug in Koop. Try using sql like below:

```sql
CREATE TABLE "ckan:services"
(
  id character varying(100),
  host character varying(100)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "ckan:services"
  OWNER TO yourUserName;
```

**Comment by hhkaos** [comment]
Thanks @dmfenton ! it works!! :dancer:
