### ISSUE TITLE
koop internal/external inconsistencies

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop#237]
Internally, `koop` is the reference for the contents of `koop/lib`. Externally, `koop` is the reference for the express middleware app that `require('koop')()` returns. This is confusing for development, has led to some bad practices internally, and imposes limitations for introspecting on processes in testing and elsewhere.

I propose we rename the express app `koop` in index, attach objects like `Cache` and `Files` that need to be instantiated onto that, and do away with indirect references to lib modules. This will take some time but I'm willing to do the bulk of the work.

**Comment by ngoldman** [comment]
@dmfenton re our discussion on IRC ^

**Comment by dmfenton** [comment]
:+1: Yes please.

**Comment by ngoldman** [comment]
Resolved in https://github.com/koopjs/koop/pull/238, awaiting review
