### ISSUE TITLE
ArcGIS API for JS does not want to render a layer created from a FeatureServer

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop#263]
From @ievgeniiK:

> Hi:
> 
> I don't know whether it's a bug, but I cannot make rendering of a featureLayer made from a FeatureServer, which is provided by Koop, work. 
> In the readme file it says that Koop works with ArcGIS JS API. I was using the example you provided on the demo page: http://koop.dc.esri.com/github/chelm/grunt-geo/forks/FeatureServer/0.
> 
> Is there's a chance I am doing something wrong or is this a bug (may be it is not supposed to work this way)?
> 
> Thank you in advance for your answer.

Copied from https://github.com/ngoldman/contact/issues/5

**Comment by jgravois** [comment]
working okay for me [here](http://www.arcgis.com/home/webmap/viewer.html?urls=http%3A%2F%2Fkoop.dc.esri.com%2Fgithub%2Fchelm%2Fgrunt-geo%2Fforks%2FFeatureServer%2F0)

**Comment by ievgeniiK** [comment]
You are right, however it is showing a different picture from what can be found by checking ".../preview". ArcGIS plots only points, whereas a layer here (http://koop.dc.esri.com/github/chelm/grunt-geo/forks/preview) looks like a collection of polylines.
And also my own geojson (http://koop.dc.esri.com/gist/772f8cfa13eb63daf838/preview) looks fine in the 'preview' mode, but does not want to be loaded in JS API (http://koop.dc.esri.com/gist/772f8cfa13eb63daf838/FeatureServer/0).

**Comment by jgravois** [comment]
the forks geojson in @chelm's [file](https://github.com/chelm/grunt-geo/blob/master/forks.geojson) is a GeoJSON FeatureCollection which contains both points and polylines.  

In the ArcGIS world, we expect an individual feature service to be limited to a single geometry type, but in [Esri Leaflet](http://esri.github.io/esri-leaflet), the `L.esri.FeatureLayer` class inherits from L.geoJson, so you get a little extra :sparkle:

**Comment by ievgeniiK** [comment]
Hm. My geojson was limited to the LineString geometry type only. 
The whole idea why I wanted to use Koop is that I could have used ArcGIS layers editing api. I need to make sure that every user gets his own layer to edit (a copy of the main layer) and Koop looks like the best solution here.

**Comment by jgravois** [comment]
@ievgeniiK i might be missing something about your own implementation, but koop provides read-only access to make external file sources look like feature services on the fly.  it does not support the [applyEdits](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Apply_Edits_Feature_Service_Layer/02r3000000r6000000/) operation (and others) of *real* feature services that make them editable.

**Comment by ievgeniiK** [comment]
Unfortunately this totally crashes my idea now. For some reason I thought that pseudo-feature services created by Koop support all the methods applicable to real feature services. Thank you for clarifying this point. But I am still truly amazed with the potential of this app!

**Comment by ajturner** [comment]
`applyEdits`

Sounds like an awesome feature request!

**Comment by dmfenton** [comment]
Looks like this discussion is resolved.
