### ISSUE TITLE
can 'out of the box' ArcGIS Open Data surface spatial items from an instance of Socrata

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop#266]
alright, the million dollar question....

can customers using ArcGIS Open Data surface content from Socrata without spinning up their own koop?

if not, can they point their own Open Data site at a custom instance?

asking for a friend...

cc/ @ajturner @astauffer @phpmaps @dmfenton

**Comment by ajturner** [comment]
Currently Koop-Socrata is not available in our hosted infrastructure. Therefore one would have to spin up their own Koop server with Koop-Socrata module installed.

This works today and is an approach being taken by a few people.

**Comment by jgravois** [comment]
thx @ajturner!

can they point an Open Data site that we host at their own koop?
if so, are they required to create ArcGIS Online items for each Socrata resource they want to include?

**Comment by ajturner** [comment]
Yes and yes. Open Data still uses AGO items for the catalog. These would be registered as the Koop proxied Feature Layers.

@jakesower is working on something to make this more automated using the DCAT feed.

**Comment by sirws** [comment]
And here is a python script that does this as well as keeps it in sync with Socrata:
https://github.com/sirws/OpenData-SocrataRegistrar

**Comment by dmfenton** [comment]
Question answered.
