### ISSUE TITLE
how to register all items from remote data portal with ArcGIS Online

### ISSUE THREAD

**Issue by mhogeweg** [koopjs/koop#271]
once you have an adaptor for some third party data portal working, what is the workflow to get all the data sources from that data portal registered as items in ArcGIS Online so that they can be used in the ArcGIS Open Data app?

**Comment by dmfenton** [comment]
Typically I just write a script that builds URLs and registers them as items. Here's an example for Socrata:
https://gist.github.com/dmfenton/7d9203e47d9bac7e9e95

**Comment by sirws** [comment]
And here is a python script that does this as well as keeps it in sync with Socrata:
https://github.com/sirws/OpenData-SocrataRegistrar

**Comment by dmfenton** [comment]
Question answered.
