### ISSUE TITLE
Determining if a field is a date has flawed logic, at least for Socrata data.

### ISSUE THREAD

**Issue by sirws** [koopjs/koop#272]
https://github.com/koopjs/koop/blob/master/lib/FeatureServices.js#L78

I have data that is coming in as a string like this "93" and it is a type string, not an Invalid Date, and !isNaN(new Date(props[key])) is true, so it is getting it's type set as a esriFieldTypeDate.

For more, see this issue:
https://github.com/koopjs/koop-socrata/issues/57

**Comment by sirws** [comment]
https://github.com/sirws/koop-socrata/commit/dcbabccae91bb99478b13c0205e9b7cc3cedd5fd
and
https://github.com/sirws/koop/commit/58067b7055d069d05ab14b2713ca371f6ee1e67d

These help alleviate the issue.  It does a better job with dates from Socrata.

**Comment by dmfenton** [comment]
This was resolved on the 3.0 branch in d38604233140f2044899f0bb57e98a69e5faa8e1
@benstoltz think you can PR the same fix into the 2.x branch?
