### ISSUE TITLE
Refactor Exporter Code

### ISSUE THREAD

**Issue by dmfenton** [koopjs/koop#273]
## Goals
- [x] Move into new repository
- [x] Replace Kue with Node-Resque
- [x] Split export sub-jobs into discrete jobs
- [x] Remove domains in favor of event-emitter pattern

### Files
 - `worker.js`: node-resque worker and logging
 - `lib/ogr.js`: all functions related to OGR
 - `lib/exportQueue.js`: exposes node-resque queue
 - `lib/upload.js`: handles saving to filesystem/s3
 - `jobs/index.js`: job base class & registry
 - `jobs/fetch.js`: fetches rows from DB and writes VRT
 - `jobs/transform.js`: wrapper over OGR to transform file
 - `jobs/copy.js`: copies latest file from one s3 bucket to another

### Job Flow

![image](https://cloud.githubusercontent.com/assets/7832202/11226679/6e535c96-8d4f-11e5-9e09-12e6ab5fcb42.png)

## Bonus Goals
- [x] Generalize beyond PG-Cache
- [x] Use single type of Export Job
- ~~[ ] Turn uploading/saving into a job that can only be run on the machine with the file~~
- [x] Reduce files on local file system
- [x] ES6

cc @jakesower @AKHarris @ngoldman

**Comment by ngoldman** [comment]
:+1:

**Comment by dmfenton** [comment]
Updated architecture to show only file system is S3. Therefore each job is atomic. It'll be more chatty, but more scalable and robust.

**Comment by dmfenton** [comment]
Done in https://github.com/koopjs/koop-exporter
