### ISSUE TITLE
Best way to access the info doc in FeatureService.js?

### ISSUE THREAD

**Issue by sirws** [koopjs/koop#274]
I am looking to make a change to the koop provider to do a better job of handling field types.  I am logging field types to the info doc.  I want to get access to the info doc in FeatureService.js but I don't want to break the API.  Any suggestions?

Thanks!
Scott

**Comment by dmfenton** [comment]
I recommend passing in the field information you need with params https://github.com/koopjs/koop/blob/master/lib/FeatureServices.js#L305
It's going to require modifying the req.params object, but I think that's the only option you have. This module is due for a major refactor anyways, so I don't have a big problem with it.

**Comment by sirws** [comment]
How do you recommend accessing koop.cache from the BaseController so we can access the info doc?

**Comment by dmfenton** [comment]
I wouldn't recommend doing that at all. You should pass in whatever you need inside the params object.

**Comment by sirws** [comment]
It looks to me like the base controller sends in the params object.  This is where I am confused.

**Comment by dmfenton** [comment]
You would need to modify the params object before calling controller.processFeatureServer. you should have already retrieved data from the db at that point

**Comment by dmfenton** [comment]
@sirws Params is on the req object here https://github.com/koopjs/koop-socrata/blob/master/controller/index.js#L209

**Comment by dmfenton** [comment]
All the feature server code has moved over to https://github.com/featureserver/featureserver
