### ISSUE TITLE
Support returning dates in feature services for UTC

### ISSUE THREAD

**Issue by sirws** [koopjs/koop#275]
I am working on improving the Socrata provider, and one thing I have found is that we should be returning dates in UTC to work like ArcGIS Online/Server based feature services.  I added some logic like this and it seems to work.  Would love to have someone review.

https://github.com/sirws/koop/commit/58067b7055d069d05ab14b2713ca371f6ee1e67d

**Comment by dmfenton** [comment]
Pull request is going to be the best way to go. But I'm cool with this in principle.

**Comment by sirws** [comment]
Here is the PR...

https://github.com/koopjs/koop/pull/277

**Comment by dmfenton** [comment]
All the code has moved over to https://github.com/featureserver/featureserver. I'll open an issue over there

**Comment by dmfenton** [comment]
moved to https://github.com/FeatureServer/FeatureServer/issues/2
