### ISSUE TITLE
CSV feature service returns count when returnCountOnly=false

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop#280]
`http://opendata.arcgis.com/datasets/f61f962c2ce84f2caa1919d425c8061d_0/FeatureServer/0/query?where=1%3D1&returnGeometry=false&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&outFields=*&f=json`

returns `{"count":249304}` but instead should return features.

**Comment by dmfenton** [comment]
Resolved in efc95d9ccbfd20ca1fe007624b195f27a05923c5
