### ISSUE TITLE
Koop Provider Request - OpenDataSoft

### ISSUE THREAD

**Issue by CarterVickery** [koopjs/koop#289]
Would like to see OpenDataSoft included as a Provider for Regional Collaboration: https://www.opendatasoft.com/

**Comment by haoliangyu** [comment]
Yeah, we have [koop-provider-opendatasoft](https://github.com/haoliangyu/koop-provider-opendatasoft), which uses its new v2 API. If there is any other question, please move the discussion to the provider repo.
