### ISSUE TITLE
Question: Koop Example

### ISSUE THREAD

**Issue by SamDrummond** [koopjs/koop#295]
Hi, I'm a consultant based out of NZ and have just completed a project using Koop.  Project uses FME Cloud, ArcGIS Online, Web AppBuilder, Koop and Electron to manage complex and large scale volume transformations and visualisation based on property development economics.

I was wondering if anyone on the project would be keen have have a demo/overview of what we have done - just for interest sake.

Regards

**Comment by jgravois** [comment]
absolutely!  we'd love to hear more about it.

**Comment by astauffer** [comment]
Shoot me some times this week that work. Most of us are in the Eastern Time Zone. We could likely connect around 9pm one night this week if that works for you?

**Comment by dmfenton** [comment]
This meeting is set so going to close the issue. Looking forward to it!
