### ISSUE TITLE
consider updating main diagram

### ISSUE THREAD

**Issue by tombuckley** [koopjs/koop#298]
has the main diagram for the project been updated in a while? 

one thing that suggests to me that it hasn't is that it says "JS API" under featureservices and then "geojson" output by koop. but it seems like feature services on AGOL now output geojson. so couldn't you also draw an arrow from featureservices back over to geojson?

**Comment by jgravois** [comment]
you make an interesting point @tombuckley.  the diagram definitely hasn't been updated in awhile.

> couldn't you also draw an arrow from featureservices back over to geojson?

my vote would be to instead replace the word feature services with ['geoservices'](http://geoservices.github.io/). i have to admit though that i don't have a horse in the race, access to the original graphic or a clue when it comes to Illustrator/GIMP so if you were willing to take the trouble of creating your own updated graphic and proposed that we use it in a pull request i'd almost certainly accept it 'as is'. 😸

**Comment by dmfenton** [comment]
what do y'all think of this graphic?
![image](https://user-images.githubusercontent.com/7832202/28444721-43eb6ea6-6d8d-11e7-8d56-3af46fd5bf88.png)

**Comment by jgravois** [comment]
now *thats* futuristic.

**Comment by tombuckley** [comment]
:) that graphic is better because its a bit more poetic. thats probably what you need in the long run? 

my horse in the race is that if there are tools in koop that would be useful to me, the existing graphic isn't helping me find them. in fact it may be leading me astray (esp in its dated specificity)

**Comment by dmfenton** [comment]
what kind of tools are you looking for?

**Comment by tombuckley** [comment]
@dmfenton thanks for asking! i ended up clicking into here:

https://github.com/koopjs

and then finding a bunch in there (e.g. s3 provider). plan to take a look in the next couple months when i have the time.

**Comment by tombuckley** [comment]
@dmfenton i'm going to just close this out. sorry, probably not my place to open it in the first place!

**Comment by jgravois** [comment]
> sorry, probably not my place to open it in the first place

no way! thats why we build it in the open! 👾
