### ISSUE TITLE
Field types when field value of first feature is null/undefined

### ISSUE THREAD

**Issue by mpayson** [koopjs/koop#299]
Hi, I have a quick question:

What's the best way to tell Koop that a field is of type `date` if the first feature has a null value for that field? It looks like Koop sets the field type by:

Grabbing the first feature in `computeAggFieldObject`:
```javascript
//...
var feature = data.features && data.features[0]
//...
  if (properties) { return computeFieldsFromProperties(properties, template, options).fields }
//...
}
```

then checking for a date object through moment.js `isValid()`
```javascript
//...
else if (typeof value === 'string' && moment(value, DATE_FORMATS, true).isValid()) 
//...
```

I'm not sure how to pass an undefined value that returns `true` for this check. Are there other possible workarounds? And for numbers, I think I should pass in `NaN`?

Thank you!

**Comment by dmfenton** [comment]
pass along metadata instead of trying to trick or finagle koop

```
{
  type: 'FeatureCollection',
  features: [],
  metadata: {
    fields: [
      {
        name: 'foo',
        type: 'string'
      }
    ]
  }
}
```

**Comment by mpayson** [comment]
Makes sense--thank you!
