### ISSUE TITLE
Repository download contains no files, only folders

### ISSUE THREAD

**Issue by WalterPayne** [koopjs/koop#300]
Hi, I tried downloading the repo without any luck.  The files are listed via the web but the downloaded ZIP file or cloned repo don't contain any files for some reason.

Any help appreciated.

Thank you.

**Comment by jgravois** [comment]
hi @WalterPayne!
that's because this repository is primarily compared of .gitmodules that point at other components that are published to npm independently.

https://github.com/koopjs/koop/blob/master/.gitmodules

**Comment by dmfenton** [comment]
@WalterPayne you are probably looking for https://github.com/koopjs/koop-core
