### ISSUE TITLE
How to configure HTTPS support?

### ISSUE THREAD

**Issue by WalterPayne** [koopjs/koop#301]
I've got my custom Koop provider working however since the server is only serving HTTP, I cannot consume it in Portal as it's expecting a HTTPS endpoint.

How do I configure Koop to respond on https?

**Comment by dmfenton** [comment]
Three options:

1. use a web server in front of Koop like Nginx that handles http and https.
2. use a loadbalancer like AWS ELB to handle https and https
3. set the Koop express server to listen for https only
- here is a good example: https://github.com/leeroybrun/node-express-https in the code example replace `app` with `koop.server`
