### ISSUE TITLE
Time aware layers

### ISSUE THREAD

**Issue by WalterPayne** [koopjs/koop#305]
Is it possible to create a time-aware layer in KOOP so that the time-sliders in the various clients are activated when consuming the service?

We can easily handle the form-date and to-date queries in the getData method.

Thank you.

**Comment by keithfraley** [comment]
the answer is yes.  We have been able to build this into our provider.

**Comment by keithfraley** [comment]
Any comments on the best way to set this up as opposed to hacking it ourselves?

**Comment by rgwozdz** [comment]
@keithfraley - Looking at the code, I think the functionality it already there.  FeatureServer looks in your provider's metadata to see if you have defined a `timeInfo` property, and if so, uses that in the layer info service (https://github.com/koopjs/FeatureServer/blob/master/src/templates.js#L54).  So try including the timeInfo in your metadata with the following spec:

```
"timeInfo" : {
     "startTimeField" : "<startTimeFieldName>",
     "endTimeField" : "<endTimeFieldName>",
     "trackIdField" : "<trackIdFieldName>",
     "timeExtent" : [<startTime>, <endTime>],
     "timeReference" : {
       "timeZone" : "<timeZone>",
       "respectsDaylightSaving" : <true | false>
     },
     "timeInterval" : <timeInterval>,
     "timeIntervalUnits" : "<timeIntervalUnits>"
}
```

Spec pulled from here: https://developers.arcgis.com/rest/services-reference/layer-feature-service-.htm

**Comment by rgwozdz** [comment]
@keithfraley noticed you have had some success with this issue on your provider (https://github.com/koopjs/koop-provider-elasticsearch/issues/11).  Was adding `time-info` to your provider's metadata enough to enable time-sliders in AGOL and Pro?

**Comment by keithfraley** [comment]
This was handled at a provider level in our case, but certainly should /
could be addressed at a winnow level

**Comment by dhatcher** [comment]
I'd say if it is handled at the winnow level you would have to make it optional.  In some cases (like when using a big data store) it is safer and faster to handle it at the provider level to keep from returning thousands of features from the store that don't fit into a given time interval.

**Comment by keithfraley** [comment]
Ok, cool, regardless, awesome addition

**Comment by rgwozdz** [comment]
That's a a great point @dhatcher, so I'd say we keep this in the provider.  I will close this, but am opening an issue in the koopjs.github.io repo to document an example of this in a provider: https://github.com/koopjs/koopjs.github.io/issues/27
