### ISSUE TITLE
PostGIS provider

### ISSUE THREAD

**Issue by brambow** [koopjs/koop#307]
Hi!  I saw Daniel's talk about Koop at FOSS4G in Boston, and it got me wondering whether I could build a provider for a PostGIS database.  I finally got around to trying it out, and got something working:

https://github.com/brambow/koop-provider-postgis

I need to do a bit of thinking about how I want the service URLs to work.  This is my first time working with koop (and my first real github repo), so any advice from your end would be welcomed.  I'm particularly wondering how I'd set up tests for this.

**Comment by dmfenton** [comment]
Thanks for sharing this @brambow! I've done a lot of work creating a postgres cache in the past and there is lots of testing. Check out https://github.com/koopjs/koop-pgcache

**Comment by dmfenton** [comment]
@brambow how has this come along?
