### ISSUE TITLE
0 coordinate values in feature don't get translated

### ISSUE THREAD

**Issue by davewilton** [koopjs/koop#309]
If geojson is created which contains 0.0 for the x value will not be projected. Tested with polygon features:

For example the following json:

https://gist.github.com/davewilton/467e84a89eb0fe08270eabfb4ae1191c

Will be returned as

https://gist.github.com/davewilton/ea5290589413ab42b16a8b81dcb9d38d

You can see it fails to project any of the values which have a longitude value of 0.

[0, 61.875] becomes [0, 61.875]
[11.25, 61.875] becomes [1252344.2714243277, 8829563.846198872]

I have verified that updating the 0 values to 0.001 the projection is performed correctly

**Comment by rgwozdz** [comment]
Fixed in https://github.com/koopjs/winnow/compare/v1.14.0...v1.15.0
