### ISSUE TITLE
Sandbox not working

### ISSUE THREAD

**Issue by davewilton** [koopjs/koop#310]
I was going to create a sandbox to demo my previous issue. However, the sandbox with no changes has errors in the console that the feature service is not found. 

![screen shot 2017-11-14 at 3 31 41 pm](https://user-images.githubusercontent.com/2278405/32763007-1487fab0-c951-11e7-9b1a-ceb06a4dfed4.png)

**Comment by rgwozdz** [comment]
Closing this, it's very old.
