### ISSUE TITLE
Using a custom symbology renderer with a geojson Feature Server

### ISSUE THREAD

**Issue by jptheripper** [koopjs/koop#312]
I am running a simple provider that reads geojson from a url and creates a featureserver.  I am trying to predefine the symbology using a unique value renderer

I cant seem to find where to pass the renderer info.

If i edit the point.json file in
<koop>\node_modules\featureserver\templates\renderers\symbology\point.json

It works perfectly, however that affects all featureServers.

**Comment by rgwozdz** [comment]
This is possible now by setting property `geojson.metadata.renderer` in the `getData` method's result of a provider.
