### ISSUE TITLE
Change default SR of koop featureserver

### ISSUE THREAD

**Issue by jptheripper** [koopjs/koop#319]
Really struggling with this one.  The default SR of koop is 4326.  I am trying to change it to 3857/102100 but I have tried everything i can and cant seem to find it.

**Comment by jgravois** [comment]
you can't just append `outSR=3857` to requests?

**Comment by jptheripper** [comment]
Unfortunately no. I'm troubleshooting the lack of functionality in Pro

**Comment by rgwozdz** [comment]
@jptheripper - I believe winnow v1.13.0 solves the pro issue.  I have not yet updated FeatureServer to use winnow v1.13.0, but you could upgrade locally and try.

**Comment by jptheripper** [comment]
I.... dont know how to do that.   I should learn

**Comment by rgwozdz** [comment]
@jptheripper see https://yarnpkg.com/lang/en/docs/cli/upgrade/

**Comment by jptheripper** [comment]
Unfortunately no change in Pro.  I see two or three icons in the complete wrong place.  there should be thousands. 
Service works fine in WAB.
Table still doesnt load (shows shape in column header) and then errors without loading data.

**Comment by rgwozdz** [comment]
@jptheripper - thanks for the additional information.  Can you confirm that you are using koop-core v3.5.4 and winnow v1.13.0?

**Comment by jptheripper** [comment]
unfortunately yes.  v3.5.4 and i manually downloaded and updated winnow to v1.13
---------------------------
Table
---------------------------
Failed to load data.

Error: 
Unknown Error
---------------------------
_OK
---------------------------

Here is the service 

https://www.mymanatee.org/giskoop/mapillary/detections/FeatureServer/0

It works in WAB without issue

my provider had to do some shenanigans due to the lack of an objectid.

**Comment by rgwozdz** [comment]
@jptheripper can you attempt to add this to Pro and load the attribute table with this service? https://koop-provider-craigslist-zdjolwgsnp.now.sh/craigslist/seattle/apartments/FeatureServer

**Comment by jptheripper** [comment]
yes that works for me.  so likely it is my provider.  bummer

**Comment by jptheripper** [comment]
i wonder if it is because my initial and full extents are null

**Comment by jptheripper** [comment]
Well, progress.  setting the extent is a massive improvement.  And now i see my error.
When i use WAB, the req.query.geomerty object is an extent with xmin, etc.  I can intercept this and translate it to lat and long for my api request that requires a bbox

Pro's req.query.geometry object looks like
{"rings":[[[-82.620500997021793,27.44003738784075],[-82.620500997021793,27.532325523433979],[-82.5282128614285568,27.532325523433979],[-82.5282128614285568,27.44003738784075],[-82.620500997021793,27.44003738784075]]],"spatialReference":{"wkid":4326,"latestWkid":4326}}

**Comment by rgwozdz** [comment]
@jptheripper glad you are making progress.  Can we close this or do you still need to be able to change default SR?

**Comment by jptheripper** [comment]
Yes lets close it.  It isnt the issue.  I still get no display in pro.  Which issue would you like me to continue that on?

**Comment by rgwozdz** [comment]
@jptheripper - I've just bumped the version on FeatureServer (v.2.10.1), which includes some minor fixes as well as the dependency bump for winnow, which I had thought would solve most of Pro issues. It does, at least, for the providers I have been using for test.

I would suggest upgrading your koop server dependencies and ensure your are using FeatureServer ^2.10.1 and ^winnow 1.13.0 and then try in Pro again.  Also, make sure you have caching for the layer turned off in Pro - I wasn't picking up the updated winnow output at first because Pro was caching old data.

If you're still having problems and your certain it isn't your provider, you could continue on https://github.com/koopjs/koop/issues/317 for rendering issue, or open a new issue for failure to load attribute table should that be your issue.

**Comment by jptheripper** [comment]
i updated featureserver to 2.10.1 and winnow to 1.13.0
I see a few dots (Like 4) but there should be thousands.  IM really baffled.  the attribute table is still throwing an error, and the dots come and go on zooming.  
It must be my provider, but my provider is very simple.  IM a bit baffled.

**Comment by rgwozdz** [comment]
Is this deployment https://www.mymanatee.org/giskoop/mapillary/detections/FeatureServer/0 up to date?  I am happy to take a look.  The behavior you described was similar for me prior to my updates of FeatureServer and winnow.  I found that Pro is highly sensitive to the contents of services...extra/unexpected properties on feature attributes seemed to cause the behavior you describe.

**Comment by jptheripper** [comment]
i am definately adding attributes on the fly, although i have them defined in the reference file

**Comment by jptheripper** [comment]
interesting thought. My reference file does not have an OBJECTID .  I add that in the provider with a hash function as there is no unique id that meets ESRI criteria (there is a string guid but it is long).  i wonder if returning and using an objectid, but not having it defined, is what is causing pro heartburn

**Comment by rgwozdz** [comment]
Ok, yes interesting.  I would put money this being a source of the problem, or at least being a good clue.  

Actually, I was just working on a separate PR in winnow for object ID generation aimed at providers that don't come with an ID.  See here https://github.com/koopjs/winnow/pull/67

**Comment by rgwozdz** [comment]
Also, I see a difference in the `fields` objects of your layer info service (i.e., /FeatureServer/0) compared to mine.  Mine has properties "editable" and "nullable".   
 
    "fields": [
        {
            "name": "OBJECTID",
            "type": "esriFieldTypeOID",
            "alias": "OBJECTID",
            "defaultValue": null,
            "domain": null,
            "editable": false,
            "nullable": false,
            "sqlType": "sqlTypeOther"
        },
     .... 

But yours is missing those properties:  

      "fields": [
        {
            "name": "OBJECTID",
            "type": "esriFieldTypeOID",
            "alias": "OBJECTID",
            "sqlType": "sqlTypeOther",
            "domain": null,
            "defaultValue": null
        }

I'm surprised they are missing as the upgrade to FeatureServer 2.10.1 should ensure those are there.

**Comment by jptheripper** [comment]
i downloaded featureserver from github and manually replaced the files and then restarted koop.  npm list does show featureserver at 2.10.1.  Maybe i didnt do it correctly.

I will add objectid as a field.

**Comment by rgwozdz** [comment]
Ok.  Just to be sure, I guess I would delete my `node_modules` directory then do:  
     $ yarn install
     $ yarn upgrade

As I look at the Fiddler output I see a difference in the `query` requests when I compare our services: yours has `outFields=value,OBJECTID`, mine has `outFields=OBJECTID`.  I wonder why Pro is creating different request parameters...?  When debugging earlier in the week, I found that have anything in addtion to OBJECTID in the `outFields` parameter caused rendering issues.

**Comment by jptheripper** [comment]
Well the OID issue was definitely my problem.  Switched to a sequence instead of hash and it renders great in Pro.  Except clicking to identify now crashes Pro.  One step forward.
