### ISSUE TITLE
Additional Documentation - How to Use

### ISSUE THREAD

**Issue by FeralCatColonist** [koopjs/koop#322]
Hi, I'm wanting to use Koop for integrating with the Waze live feed. After reading through the readme, I was totally lost about how to even start using Koop. 

I'd really like to see more detailed documentation or a getting started guide. Additionally I'd be interested in helping  to get a dedicated Waze repository up running.

**Comment by rgwozdz** [comment]
@GISspellbladeCG have you looked at http://koopjs.github.io/?

**Comment by GISspellbladeCG** [comment]
I've looked at that, still very confused. I'm unsure how to translate the use-case from a site like Yelp/Zillow to a live xml feed like Waze.

My familiarity with JavaScript is low, having done little except make small edits to web apps. Mostly experienced in Python/R; I guess I'm looking for a Kung-Fu Panda-esque "level 0" style guide.

**Comment by rgwozdz** [comment]
@FeralCatColonist - this should help: https://www.youtube.com/watch?v=mhdLEUuE3dk&ab_channel=EsriEvents
