### ISSUE TITLE
How to use services within ArcMap

### ISSUE THREAD

**Issue by bmulcahy** [koopjs/koop#326]
How do you use the services provided by koop from within ArcMap?

**Comment by rgwozdz** [comment]
I've used with ArcGIS Pro.  You should be able to use Koop URLs in place of ArcGIS server URLs.  For example in ArcGIS Pro I do: Add Data -> Data From Path, then paste in my koop url.  If you were using the [file-geojson provider](https://github.com/koopjs/koop-provider-file-geojson), for example, the url would be http://localhost:8080/file-geojson/rest/services/polygon-sample/FeatureServer/0

**Comment by bmulcahy** [comment]
Thanks!

**Comment by Balmark** [comment]
Hi .. that's fine for ArcGIS Pro .. but you can't seem to do this from ArcMap 

I've also tries adding http://localhost:8080/file-geojson as an ArcGIS Server in the hopes it would list the layers, but it just gets added with no children (ie no list of map services)
