### ISSUE TITLE
Support Stream Services

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop#332]
Would it be possible to support [Stream Services](http://www.arcgis.com/home/search.html?q=typekeywords%3A%22Stream%20Service%22&start=1&sortOrder=desc&sortField=relevance&focus=layers) as an output? something [like this](https://geoeventsample1.esri.com:6443/arcgis/rest/services/LABus/StreamServer) would be awesome :smile: 

Best regards,
Raul

**Comment by rgwozdz** [comment]
My understanding is that this would be a new type of output service based on a websocket connection.  Would be very cool to try.

**Comment by keithfraley** [comment]
I agree, this would be pretty cool.

**Comment by hhkaos** [comment]
Just FYI, [@NTKOG](https://github.com/ntkog) and me have been working on an [arcgis_websocket_server](https://github.com/esri-es/arcgis_websocket_server) which is going to be used to stream tweets in real time to an app using the [StreamLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-StreamLayer.html) at JSAPI 4.x. 

> **Note**: the twitter emitter is not publicly share yet, but it will.

We have also tested it against a webmap and it worked. Today it's only working with the latests versions of the JS API as [we explained here](https://github.com/esri-es/arcgis_websocket_server#arcgis-api-for-javascript-version--v48--v3x).

BTW, any [help/contribution](https://github.com/esri-es/arcgis_websocket_server/issues) is also more than welcome :stuck_out_tongue_winking_eye: :rofl: 

Cheers!

**Comment by rgwozdz** [comment]
Output plugins can now use the `pullStream` method, so long as the linked providers include a `getStream` method.  Docs forthcoming.

**Comment by hhkaos** [comment]
Looking forward for this @rgwozdz , would you mind letting me know when then docs are ready?
