### ISSUE TITLE
New koop provider for Strava

### ISSUE THREAD

**Issue by Jking-GIS** [koopjs/koop#333]
Recently made a new koop provider for Strava. Wanted to make you guys aware: https://github.com/Jking-GIS/koop-provider-Strava

**Comment by Jking-GIS** [comment]
@rgwozdz Cool! I don't think I have any sort of new branch push permissions on that repo though.

**Comment by rgwozdz** [comment]
Hey @Jking-GIS - rather than branch, you can fork the repo to your own personal github, make the changes, then submit the fork as a PR.

**Comment by Jking-GIS** [comment]
@rgwozdz Done. Thanks, didn't realize you could do that

**Comment by rgwozdz** [comment]
Now added to docs.
