### ISSUE TITLE
Custom FeatureServer Url

### ISSUE THREAD

**Issue by sahbijabnouni** [koopjs/koop#335]
I am writing a new koop provider and I want to custom the default url. Is it possible with the new version
if yes, is there any doc?
Requirement:
instead of the default one
/iasWorld/FeatureServer/:layer/:method':
I want
/iasWorld/:table/FeatureServer/:layer/:method

**Comment by rgwozdz** [comment]
@sahbijabnouni - check out **output-services route parameters** on the [provider specification page](http://koopjs.github.io/docs/specs/provider/) and consider prefixing your routes during provider registration (for example, `koop.register(provider, { routePrefix: '/api/v1})`.

With route parameters `:hosts` and `:id` and route prefixing, you should be able to customize to your needs.

**Comment by sahbijabnouni** [comment]
Thanks  rgwozdz.
I have a question about the koop logger.
I did not find documentation. How to set the logging configuration.

**Comment by rgwozdz** [comment]
@sahbijabnouni - can you open another issue?  Closing this.
