### ISSUE TITLE
Method not supported

### ISSUE THREAD

**Issue by sahbijabnouni** [koopjs/koop#337]
Hi ,

I got a "Method not supported" error when enabling hosts:

const provider = {
    type: 'provider',
    name: 'iasworld',
    hosts: true, 
    disableIdParam: false,
    Controller: require('./controller'),
    Model: require('./model'),
    routes: require('./routes'),
    version: require('./package.json').version
  }
  
The request was sent successfully but, I got the error when calling the callback to return data.

**Comment by rgwozdz** [comment]
@sahbijabnouni - please post the request url so I can take a look.

**Comment by sahbijabnouni** [comment]
iasworld/ias/PARCEL_METADATA_TAXYR/FeatureServer/0/query?dbfilters=taxyr=2008

pattern:
:provider/:host/:id/FeatureServer/0/query

**Comment by rgwozdz** [comment]
Ok.  Can you attach or link to your provider code?

**Comment by sahbijabnouni** [comment]
https://drive.google.com/file/d/1xcNNrzZuD4e12DfUUtVc-2wmnQ6e4Cwj/view?usp=sharing

**Comment by rgwozdz** [comment]
@sahbijabnouni Do you get the Method Not Supported error with requests from the Esri JS API?

**Comment by rgwozdz** [comment]
You will get the Method Not Supported error when using the Esri JS API to register koop feature layers if you don't use the the routes with `rest/services` included in the url.  So you would want to use:

`iasworld/rest/services/ias/PARCEL_METADATA_TAXYR/FeatureServer/0/query?dbfilters=taxyr=2008`
