### ISSUE TITLE
Koop + aws api gateway + lambda

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop#340]
Has anyone tested AWS API Gateways with Koop and Lambda. Seems serverless might actually be a reality at some point. This would be extremely powerful for multiple reasons, one is it would allow you to scale unique authentication per service or per group of services.

**Comment by simon-fisher** [comment]
Keith, did you ever have any luck with this?  I'm trying to deploy koop provider to aws lambda.  None of the samples I've tried seem to work. There are always errors on the "npm run lambda-create"

**Comment by keithfraley** [comment]
I have not had a chance to look at this yet, but I would love to work
together with you on it as it is still on our roadmap

**Comment by haoliangyu** [comment]
We have created another example project to demonstrate how to deploy a Koop server to AWS Lambda + API Gateway. This example uses the [serverless](https://github.com/serverless/serverless) framework for AWS deployment and management.

Please try https://github.com/koopjs/koop-serverless-example and let us know if you still see any error.

**Comment by simon-fisher** [comment]
Awesome thanks.  I'll be working through the in the next day or so. I'll let you know hope it goes.

**Comment by keithfraley** [comment]
brilliant, cant wait to dig in

**Comment by haoliangyu** [comment]
Hey @simon-fisher  @keithfraley does the example work for you?

**Comment by simon-fisher** [comment]
Yes it did.  I'm having some issues getting my own provider to work, but working through that still.
