### ISSUE TITLE
CORS middleware not working when authentication enabled?

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop#342]
// Plugin our cors middleware
    var corsOptions = {
        origin:  'https://www.xxxx.com:3344',
        optionsSuccessStatus: 200 
    }
    this.express.use(cors(corsOptions));

plugging CORS middleware seems to work for koop instances that dont have authentication plugin, but when authentication is enabled it seems to be not working as designed.  The code above works for non authenticated, but not sure authenticated. Any thoughts?

**Comment by rgwozdz** [comment]
Hey @keithfraley, a couple of questions, thoughts.  

1) Can you attach the client error you are receiving that indicates CORS problem?

2) Just an FYI, Koop already enables CORS by default and sets it wide-open;  see https://github.com/koopjs/koop-core/blob/master/src/index.js#L86

3) Can you give some more context to the code snippet above? Is it just pseudo-code?  I'm not sure where the `this.express` comes from.  If you wanted to add CORS to the underlying express app of a koop instance, I think you would do it in the koop server file, and in that case it would be more like:

```
koop.server.use(cors(corsOptions));
```

**Comment by keithfraley** [comment]
Access to XMLHttpRequest at 'https://internal_portal_where_koop_layer_is_authenticated_and_stored_as_item.com/rest/services/...' from origin 'https://internal_location_of_Webappbuilder_developer_edition:3365' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.


This is a chrome error, does this help?

**Comment by rgwozdz** [comment]
Okay, thanks.  Can you paste or attach the contents of your koop server file?

**Comment by keithfraley** [comment]
looks like WAB works fine internally with AGOL webmaps, just not the internal portal

**Comment by rgwozdz** [comment]
@keithfraley and I troubleshot this one; was not related to Auth plugin.  When attaching Koop to router of a separate Express instance, you can override Koop's internal CORS settings by setting CORS **after** attachment of Koop, e.g.:

```
this.express.use('/koop', this.koop.server);
this.express.use(cors(corsOptions)); 
```
