### ISSUE TITLE
use koop in nodejs frameworks i.e sailsjs or fasitify 

### ISSUE THREAD

**Issue by mapsgeek** [koopjs/koop#346]
i have been trying to run koop as a part of my API which is built using sailsjs, i tried to use koopjs as a middleware and registered it as mentioned in the docs and the way sailsjs is using middlewares, the server starts and logs from koop appears with various endpoints from providers but the routes never get attached to the port, i tried with fasitify since it's more closer layer to express but got the same result, it only works with bare express.
is there any suggestion or help regarding this ?

**Comment by rgwozdz** [comment]
Koop is pretty tightly coupled with Express.  I would imagine problems trying to add it to other frameworks.

**Comment by mapsgeek** [comment]
regarding this issue, i found out that some nodejs frameworks which actually built on top of express aren't compatible with many express middlewares not just koop, i switched to nestjs which actually " better " by itself as a framework but actually also support the express native `app.use()` and achieved the goal.
