### ISSUE TITLE
Google Auth

### ISSUE THREAD

**Issue by geopast** [koopjs/koop#349]
Hi folks,
Been trying to implement the google-sheets provider however cannot seem to authenticate to access the Google Sheet. [In the Google console](https://console.cloud.google.com/apis/api/sheets.googleapis.com/credentials), when you go to create credentials for the Google Sheets API specifically, the 2 options listed are: OAuth 2.0 and Service Accounts. The Koop documentation and code appear to expect an API key. Am i missing something?
Thanks,
Neil

**Comment by rgwozdz** [comment]
@geopast - when I set mine up, I added a Service Account.  On that service account's details page you can create one or more keys.

**Comment by geopast** [comment]
@rgwozdz - thanks. I put the key from a new service account into config/production.json and config/custom-environment-variables.json. I've already enabled the Google Sheets API. When I test with curl, I still get the same error:

`[ec2-user@ip-123-123-123-123 ~]$ curl https://google-sheets-provider-77dd8oha9.now.sh/googlesheets/MYPAGEID/sydney%21A1:H/FeatureServer/0/query?returnCountOnly=true
The page could not be found

FILE_NOT_FOUND
`

**Comment by rgwozdz** [comment]
Just to be sure I am following you;  when you do the curl, you are replacing `MYPAGEID` with the key from Google?

**Comment by rgwozdz** [comment]
@geopast - I may have lead you the wrong way.  Taking another look at Google console, you want to go to: 
APIs & Services -> Credentials
Then create an API key.

**Comment by geopast** [comment]
@rgwozdz Hi Rich, yes that's right - the MYPAGEID is the actual sheet ID in this case. I did create an API key using the method you describe (that's what I did originally) but that gave me the error I mentioned previously. When I go into the Google Sheets API page, the "Credentials compatible with this API" does not list API as an option - only OAuth and Service Account. That led me to think maybe the auth options have changed with Google Sheets which would impact this Koop provider.

![image](https://user-images.githubusercontent.com/10397157/60319455-cbe08800-99b9-11e9-901f-6139f052cbe1.png)

**Comment by rgwozdz** [comment]
@geopast - I think you are in the wrong place.  Here's the screen grabs showing where and how I created my key:
<img width="300" alt="goog-1" src="https://user-images.githubusercontent.com/4369192/60597591-06527800-9d60-11e9-94de-66491de1df52.png">

and then:

<img width="500" alt="goog-2" src="https://user-images.githubusercontent.com/4369192/60597603-09e5ff00-9d60-11e9-8d72-9b031e322c06.png">

**Comment by geopast** [comment]
@rgwozdz - thanks. Yes that's what I did try initially. I just tried again but still getting error - The page could not be found. I added the api key to the 2 files in config/. Then pushed the code to Now.sh and tried the curl test:

`curl https://google-sheets-provider-hguguuekb.now.sh/googlesheets/1uFxEwaXA2oJLRMI72v8EQrc7s6tr8CKFN-nAwos0m5I/sydney!A1:H/FeatureServer/0/query?returnCountOnly=true`

Would you be willing to try it from scratch? From what i've read, API should work!

**Comment by rgwozdz** [comment]
@geopast - I tried it from scratch and it worked for me.  Just to be clear on the url form (the provider's readme isn't very clear, I will update ASAP):

`curl https://<domain>/googlesheets/<page-id-for-google-sheets-workbook>/<sheet-name>!A1:<letter-of-last-column-in-header-row>/FeatureServer/0/query`

Your getting a 404 error, which suggests something wrong with either Now, your url form, or the google-workbook page id. So, two follow-up questions. 
1. Have you tried this on localhost and also received the 404?
2. Did you add the Google Sheets API to the key you generated? See screengrab.
![Restrict_and_rename…_–_APIs___Services_––_Google_Cloud_Platform](https://user-images.githubusercontent.com/4369192/60676500-e2f8fd00-9e33-11e9-8f1e-a05e6ae54b60.jpg)

**Comment by rgwozdz** [comment]
@geopast - any update on this?
