### ISSUE TITLE
Alternative Provider : koop-provider-csv

### ISSUE THREAD

**Issue by ntkog** [koopjs/koop#351]
Hi!  

I've developed an alternative version for koop-provider-csv . You can check it out: [@ntkog/koop-provider-csv](https://github.com/ntkog/koop-provider-csv#readme)

[NPM package](https://www.npmjs.com/package/@ntkog/koop-provider-csv) 

[An example](https://github.com/ntkog/taller_desarrollo_partners_2019/tree/master/procesamiento_datos/koop_cli/examples/csv-provider) 

Here you have some reasons why I've decided to build another version instead of doing a PR for the existing [koop-provider-csv](https://github.com/haoliangyu/koop-provider-csv) : 

- Trying an alternative way to process streams with [stream-chain](https://www.npmjs.com/package/stream-chain) . IMHO has performance and expressiveness advantages when you have to build a transformation pipeline. 
- Some code optimizations ( better memory usage). You will notice if you try it out :-)
- The previous csv provider **fails** with some **valid csv's ** ( I attached one example) .  One of the dependencies [csv-reader](https://www.npmjs.com/package/csv-reader) doesn't parse csv properly as anyone would expect. If you test it with the csv file provided here, you will notice that **parses latitude field as a string instead of a number** 

[m30.csv.zip](https://github.com/koopjs/koop/files/3360187/m30.csv.zip)

> In this provider I skipped [autodetect-decoder-stream](https://www.npmjs.com/package/autodetect-decoder-stream), but it can be added easily, for example, [here on line 47](https://github.com/ntkog/koop-provider-csv/blob/master/src/model.js#L47)

Hope people find useful, 

Cheers!

**Comment by rgwozdz** [comment]
Thanks for the contribution @ntkog.  I've referenced your provider here https://koopjs.github.io/docs/available-plugins/providers#third-party.
