### ISSUE TITLE
New koop-provider-carto

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop#353]
I have just released a new provider: https://www.npmjs.com/package/koop-provider-carto

Would it be possible to add it to the [Third party providers](https://koopjs.github.io/docs/available-plugins/providers#third-party)?

Thanks!

**Comment by rgwozdz** [comment]
@hhkaos - if branch the docs and add it [here](https://github.com/koopjs/koopjs.github.io/blob/master/_docs/available-plugins/providers.md) and submit PR.  I should be able to review today.

**Comment by hhkaos** [comment]
Done! thx! https://github.com/koopjs/koopjs.github.io/pull/66
