### ISSUE TITLE
Feature Service Unable to Styled in ArcGIS Online Web Map (Classic)

### ISSUE THREAD

**Issue by chanbot5000** [koopjs/koop#356]
I have a feature service created using Koop, added as an item to ArcGIS Online, that does not allow for 'change style' in the ArcGIS Online Web Map viewer (classic). Please see the screenshot below.

The feature service item has been in operation with our ArcGIS Online account for over a year yet recently began behaving oddly. 

However, the feature service is able to be styled in the new Beta Web Map viewer. Sometimes the feature service does not display any data at all, and the subsequent Operations Dashboards fail to load any data, but then the data suddenly re-loads and displays on screen.

In the Beta Web Map viewer the expressions sometimes work, but often fail after reloading, causing the user to be unable to X out of the expression menu.

Has anyone else experienced an issue of not being able to style a Koop service by attribute?

Thanks!

![image](https://user-images.githubusercontent.com/1258334/71380220-3b0ef180-2583-11ea-9b32-ca9cbcf3676c.png)

**Comment by rgwozdz** [comment]
@chanbot5000 - so it was just recently that all of these issues began?  Is it possible that the remote API that your provider is connecting to has changed?

Can you provide a URL to your feature service so I can inspect?

**Comment by chanbot5000** [comment]
> @chanbot5000 - so it was just recently that all of these issues began? Is it possible that the remote API that your provider is connecting to has changed?
> 
> Can you provide a URL to your feature service so I can inspect?

We noticed the behavior changed in early December. However, when we request the data from the API it doesn't appear to have changed. It returns a simple JSON which is converted into the feature service format and served up. 

Unfortunately, the URL to the feature service is secured so I'm not sure we can get you access to inspect.

**Comment by rgwozdz** [comment]
@chanbot5000 that doesn't give us very much to go on.  Are you getting client side errors in Dev Tools that you can share?

FYI, we haven't released anything new to the feature service output plugin since October.

**Comment by chanbot5000** [comment]
@rgwozdz Yes I understand that troubleshooting without access to the feature service will be challenging. I could possibly share the item with your ArcGIS Online account to see if you can access it, but there may be another level of authentication required.

Here is a screenshot of the client side error we are seeing in the classic map viewer when clicking Change Style > Location (Single Symbol) Options button:
![image](https://user-images.githubusercontent.com/1258334/71381203-6693db00-2587-11ea-893b-26e39254ed21.png)

**Comment by haoliangyu** [comment]
This is likely an issue of the AGOL. Using the new map viewer is a workaround.

**Comment by rgwozdz** [comment]
closing as inactive.
