### ISSUE TITLE
Koop-cache-memory and empty responses in combination with date filters

### ISSUE THREAD

**Issue by johngalambos** [koopjs/koop#360]
When the default in memory cache is enabled, the first feature service query with a date filter will work and all subsequent queries will return empty results.

I've written a simple provider that reproduces this behavior here: https://github.com/johngalambos/koop-date-repro-provider

If you run this koop instance with this query, it will correctly return the one result on the first query. Each subsequent query will return empty results as long as the cache has not expired.

http://localhost:8080/date-repro/test/FeatureServer/0/query?f=json&where=(dateUpdated%20%3C%20timestamp%20%272020-04-02%2006%3A59%3A59%27)%20AND%20(1%3D1)

Note that I have specified the correct fields metadata etc.

I did try to trace this down as best I could and I think it's related to several things:

- The geoservices output provider updates the cache with string dates translated to integers

- I think there may be some kind of conflict when the first query is against ISO date strings in AlaSQL and the subsequent queries are against integers. I couldn't figure out if this was due to a compiled query or the like.

- The geoservices output provider mutates default cache entries without using cache update, insert functions, translating dates to integers.

I'm still pretty new to the architecture so not sure how best to fix this. I know similar topics have been discussed here: https://github.com/koopjs/koop/issues/358

and this may also be related to: https://github.com/koopjs/winnow/issues/108

To work around this I created a custom cache that is really close to the default in memory cache with the exception it translates all date integers back to iso strings on upsert and it deep clones values returned from the cache to prevent the geoservices output provider from mutating them.

Thank you for the wonderful project!  This has been truly helpful setting up some quick integrations over the last couple of weeks.

**Comment by rgwozdz** [comment]
@johngalambos - I think another work around is to set `metadata.fields` parameter in your getData method.  See https://koopjs.github.io/docs/development/provider/model#adding-provider-metadata-to-the-geojson.  I think this prevents unwanted transformation of date fields.

**Comment by johngalambos** [comment]
@rgwozdz, I did try this in the repro: https://github.com/johngalambos/koop-date-repro-provider/blob/563c1c47eb1ace38d1ad0910f5c2aae79fc6fa42/src/model.js#L33.. Is there some other combination of types I should be using?

**Comment by rgwozdz** [comment]
Ok, thanks for sharing that.  I had hoped that might help.  We'll make a fix for this a priority.

**Comment by rgwozdz** [comment]
Pretty sure this was fixed a while back.
