### ISSUE TITLE
Firebase Api to ArcGIS Online

### ISSUE THREAD

**Issue by ashad9alif** [koopjs/koop#364]
I have created an api from firebase which is a live datasets. I have created the koop Provider using Node.js following the sample provider. I can see the data in browser from localhost8080. Now i cant add it to the Arcgis online using Add from web. 
How can i do that? Do i need to creat an output plugin or adapter? or do i need to deploy the app in an https server.

**Comment by haoliangyu** [comment]
No need to create a plugin or adapter. Once you have a locally running Koop  and the API is working correctly, you can deploy the app to a cloud service and expose the endpoint. Then you can add this as a feature service item at ArcGIS Online.

Depending on the use case, you can deploy the app as a normal server or a serverless app. If you can share more about the use pattern, we may be able to provide more help.

**Comment by haoliangyu** [comment]
If you happen to deploy it to Heroku, we have a proposing deployment guide: https://github.com/koopjs/koopjs.github.io/blob/6fd390c11950d7d6af25e7476184475276ae0c39/_docs/deployment/heroku.md

**Comment by rgwozdz** [comment]
Please see the new deployment docs. https://koopjs.github.io/docs/deployment
