### ISSUE TITLE
SQL Parser: error parsing character '

### ISSUE THREAD

**Issue by mcasamayorpolo** [koopjs/koop#369]
I have gotten an error in Koop when I make queries to fields whose value is a string with the character '.

An example is the Feature Layer that has the field _description_ and the feature that I want to get has the _description_ field value: _BRANDON’S WAREHOUSE_.

When I do a query to get this feature, the SQL where clause is:

where = ((UPPER(description) = 'BRANDON’’S WAREHOUSE'));

An error parsing happens and the response is the following:

{"error": "Expected \"!=\", \"%\", \")\", \"*\", \"+\", \",\", \"-\", \"--\", \"/\", \"/*\", \"<\", \"<=\", \"<>\", \"=\", \">\", \">=\", \"AND\", \"OR\", or [ \\t\\n\\r] but \"'\" found."}

How could I do this query without error?

Thank you so much in advance.

**Comment by haoliangyu** [comment]
Your where clause has an issue. The `UPPER(description) = 'BRANDON’’S WAREHOUSE'` already returns a boolean value and `where = true/false` is a wrong syntax. You can try

```
where UPPER(description) = 'BRANDON’’S WAREHOUSE'
```

**Comment by mcasamayorpolo** [comment]
I have tried:

**where UPPER(description) = 'BRANDO''S WAREHOUSE'**

and it doesn't work.

**Comment by rgwozdz** [comment]
@mcasamayorpolo Are you getting the same error?  I have tried @haoliangyu's solution and found it to work without any error.

**Comment by mcasamayorpolo** [comment]
Yes, I have the same error with my clause. I have tried the @haoliangyu's solution and I haven't got an error but I haven't got the feature. I think that the clauses haven't the same character. 

@haoliangyu's clause: where UPPER(description) = 'BRANDON’’S WAREHOUSE'
My clause: where UPPER(description) = 'BRANDON''S WAREHOUSE'

The main issue is that the data base has the value registered as BRANDON'S WAREHOUSE, so I can't get this feature.

**Comment by rgwozdz** [comment]
@mcasamayorpolo - Try this:
`UPPER(description) = "BRANDON\'S WAREHOUSE"`

**Comment by rgwozdz** [comment]
@mcasamayorpolo - Sorry. Disregard, I think we need to add some special handling to support this. Hope to patch soon.

**Comment by rgwozdz** [comment]
@mcasamayorpolo - we have just released an update to Winnow (v2.1.1) that fixes this issue.  If you reinstall Koop you should get this updated version of Winnow.  You should now be able to escape single quotes by preceding it with an additional single quote.  Meaning, this should work now:
`where UPPER(description) = 'BRANDON''S WAREHOUSE'`

**Comment by mcasamayorpolo** [comment]
I have updated to Winnow (v2.1.1) and I don't get the error but I can't get the feature that I am querying. As you can see in the following image **the features array is empty**.

![KoopResponse](https://user-images.githubusercontent.com/36007446/98924080-ba2b5200-24d4-11eb-9eaf-1c6785707079.PNG)

**Comment by rgwozdz** [comment]
Ok, please send the request URL you are using, and if you can the raw data (the data that Koop is getting from the remote API) that include the feature that your query is targeting. 

Take a look at the [unit test](https://github.com/koopjs/winnow/blob/master/test/integration/filter.spec.js#L523-L528) we've added to test this type of query:

```js
test('with escaped single quote in query', t => {
  const options = {
    where: "Street_Name = 'GRAND''S STREET''S'"
  }
  run('trees', options, 1, t)
})
```

Which operates on this fixture:

```json
{
            "type": "Feature",
            "properties": {
                "OBJECTID": 11303,
                "Common_Name": "SOUTHERN MAGNOLIA",
                "Genus": "MAGNOLIA",
                "Species": "GRANDIFLORA",
                "House_Number": 505,
                "Street_Direction": "S",
                "Street_Name": "GRAND'S STREET'S",
                "Street_Type": "AVE",
                "Street_Suffix": null,
                "Trunk_Diameter": 13,
                "Longitude": -118.162307,
                "Latitude": 34.137114,
                "survey_date": "2017-01-05T00:00:00.000Z"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -118.16230746759626,
                    34.137113646321595
                ]
            }
        },
```

**Comment by mcasamayorpolo** [comment]
The feature I want to get is the following:

> 

            "type": "Feature",
            "properties": {
                "OBJECTID": 41,
                "id": 41,
                "description": "BRANDON'S WAREHOUSE"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -102.071082,
                    19.354756
                ]
            }

 And the request URL I am doing is the following:

[https://localhost:8443/gsv/warehouses/FeatureServer/0/query?f=json&where=((UPPER(description)%20%3D%20%27BRANDON%27%27S%20WAREHOUSE%27))&returnGeometry=false&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-11362509.53184058%2C%22ymin%22%3A2196743.2468854175%2C%22xmax%22%3A-11362492.214076364%2C%22ymax%22%3A2196751.83112199%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100](url)

**Comment by rgwozdz** [comment]
@mcasamayorpolo - it's not working for you because your `where` parameter has an exterior set of parenthesis.  If you url decode the URL you will see this:

`where=((UPPER(description) = 'BRANDON''S WAREHOUSE'))`

Without the outer set of parenthesis, I find it works.  Tested both of these:

`where=(UPPER(description) = 'BRANDON''S WAREHOUSE')`
`where=UPPER(description) = 'BRANDON''S WAREHOUSE'`

Is there a particular client that is constructing that `where` parameter?

**Comment by rgwozdz** [comment]
@mcasamayorpolo anything more on this?

**Comment by mcasamayorpolo** [comment]
It works fine! Thank you so much! 👍
