### ISSUE TITLE
Update a unique module

### ISSUE THREAD

**Issue by mcasamayorpolo** [koopjs/koop#372]
Hi everyone!
I would like to update a unique module in Koop, is it possible? In this case, how should I do it? 
Thank you so much in advance.

**Comment by haoliangyu** [comment]
@mcasamayorpolo  Can you explain more on the "unique module" you want to update and your use case?

**Comment by mcasamayorpolo** [comment]
I need to update Winnow  to version v2.1.1. But I would like to update only this specific module.

**Comment by haoliangyu** [comment]
You can still install the `winnow` module even it is not explicitly used in your source code:

```
npm install winnow@^2.1.1
```

That should force updating the package-lock.json file.

**Comment by mcasamayorpolo** [comment]
It works fine! Thank you so much! 👍
