### ISSUE TITLE
Koop-cache-memory: queried by date field gets empty responses

### ISSUE THREAD

**Issue by mcasamayorpolo** [koopjs/koop#373]
Hi,

I use the Koop-cahe-memory and when I filtered the data by a date field, I get empty responses. 

https://localhost/KoopTest/data1/FeatureServer/0/query?f=json&where=(dateUpdate%20BETWEEN%20timestamp%20%272020-09-30%2022%3A00%3A00%27%20AND%20timestamp%20%272020-11-30%2023%3A00%3A00%27)

![image](https://user-images.githubusercontent.com/36007446/107514924-98f90100-6baa-11eb-91e5-b1056dc4ffba.png)

**Comment by rgwozdz** [comment]
Hi @mcasamayorpolo, can you look in your package.json or node_modules directory and let me know  which version of Koop you have installed?  I think the latest version (4.1.0) may resolve the issue you are reporting.

**Comment by rgwozdz** [comment]
@mcasamayorpolo anything new on this?
