### ISSUE TITLE
False Console Warnings

### ISSUE THREAD

**Issue by AvidDabbler** [koopjs/koop#375]
Hey I am having a couple of issues with working with non date numbers that are unique id's where Koop is interpreting them as Dates. I am also working with a date that Koop interprets as a number. Is there TypeScript Support or a way to manually configure the data types?

**Comment by AvidDabbler** [comment]
Issues have been resolved with the Async task issues. Problem was with using an async reduce function. Console warnings still persist.


```
WARNING: requested provider's metadata field "trip_id (Integer)" not found in feature properties)
WARNING: requested provider's metadata field "vehicle_id (Integer)" not found in feature properties)
WARNING: requested provider's metadata field "start_date (Date)" not found in feature properties)
WARNING: requested provider's metadata field "schedule_relationship (String)" not found in feature properties)
WARNING: requested provider's features have property "route_id (String)" that was not defined in metadata fields array)
WARNING: provider's "idField" is set to OBJECTID, but this field is not defined in metadata.fields
```

**Comment by rgwozdz** [comment]
Hello @AvidDabbler - sorry I missed this when first posted.  There's been quite a bit of refactoring and several releases since this was posted.  Are you still using Koop, and if so, wondering if you are still experiencing this.  Koop is now published as `@koopjs/koop-core` and is on version 8.0.2.

**Comment by AvidDabbler** [comment]
No I’m not using Koop anymore. I pivoted away from Koop but was working on
building a data lake query with aws Athena.
