### ISSUE TITLE
Using Koop FeatureServer in ArcGIS Online

### ISSUE THREAD

**Issue by simonfisher16** [koopjs/koop#377]
Has anyone been able to load a Koop Feature Service in ArcGIS Online?  Either add it as a content layer or add it to a map?  if so do you have a sample service?

Thanks
Simon

**Comment by AvidDabbler** [comment]
I have, but you have to use the classic map app. I am trying to get Esri's attention as the only way to add it to portal is the classic map currently.

**Comment by AvidDabbler** [comment]
https://github.com/koopjs/koop/issues/379

**Comment by bsvensson** [comment]
@simonfisher16  - seems to work fine with the current version of the map viewer:
 * https://www.arcgis.com/apps/mapviewer/index.html?url=https://scoop.iotrans.it/vehicles/FeatureServer/ 
 * https://www.arcgis.com/apps/mapviewer/index.html?url=https://scoop.iotrans.it/stops_otp/FeatureServer/

**Comment by simonfisher16** [comment]
@bsvensson 

Those urls don't work for me

**Comment by AvidDabbler** [comment]
I terminated those services, but they did work

**Comment by rgwozdz** [comment]
As long as you are adding the FeatureServer route that includes the `rest/services` fragment, it should work.

**Comment by droberge2015** [comment]
I have a featureServer from a vendor (Trimble) , I can display the information just fine but I CAN'T filter the data (Date filed) the same way I could do on a TRUE hosted Feature Layer in ArcGIS Online. I created a copy of the data hosted as a true Feature Layer and see the different option for filtering the same Date field

Filter option from the Koop featureServer layer:
![image](https://user-images.githubusercontent.com/11433967/185412416-e1f9eb68-3744-4577-a555-04a31c86ae15.png)


Filter option from a copy of the Koop layer hosted as a Feature Layer
![image](https://user-images.githubusercontent.com/11433967/185412628-fb5b79ce-92f9-4b71-8971-5143b75e7d21.png)


Why would the Filter option be different? it would be so nice to be able to get the same options...

Thanks!

**Comment by rgwozdz** [comment]
@droberge2015 - that is curious.  I'm pretty sure the drop down values don't come from the service, but rather, the UI.  That said, I wonder if they are based on the ArcGIS server version.  Koop provides a default version that may have been different than the version used by the hosted feature layer.

In any case, I'm closing this issue since it was about services not working in AGO.  If you'd like to open a new issue, we can pick it up there.
