### ISSUE TITLE
New AGOL/Portal cannot add Koop service

### ISSUE THREAD

**Issue by AvidDabbler** [koopjs/koop#379]
I am building my start up with KoopJS at the moment and I am having an issue where the only way that I can add a service to the portal is through the classic map viewer service on AGOL. 

I have tried three different ways:
- through the add a service (both as a url and a feature service url
- through the new map viewer application
- through the classic map viewer application

Here is the link to one of my Koop services that is working fine AGOL just so long as I import and save via the Classic Map View App

[Koop Service](https://scoop.iotrans.it/current_stops/FeatureServer/)

**Comment by bsvensson** [comment]
@AvidDabbler - seems to work fine the current version of the map viewer:
 * https://www.arcgis.com/apps/mapviewer/index.html?url=https://scoop.iotrans.it/vehicles/FeatureServer/ 
 * https://www.arcgis.com/apps/mapviewer/index.html?url=https://scoop.iotrans.it/stops_otp/FeatureServer/

**Comment by AvidDabbler** [comment]
@bsvensson I can confirm that you can add in a new layer with the new map viewer, but I am not able to save the layer to the portal after I add it in. This is still functionality that is only available in map viewer classic. 

I am unable to get a screenshot of the classic, but here is the documentation on how to save layers in the map
https://doc.arcgis.com/en/arcgis-online/reference/copy-save-layers.htm#ESRI_SECTION1_9F4C867CA85B4E4DA5945EF1C8BBC3E0

![new map viewer layer properties](https://user-images.githubusercontent.com/8471756/152903326-d3075d97-511c-4566-a984-c4aed7e85008.png)

**Comment by odoe** [comment]
The note at the top says that save functionality is only in classic, not the new map viewer yet.

> This functionality is currently only supported in Map Viewer Classic. It will be available in a future release of Map Viewer.

Can you save it as an item in your content page first, then add it to the new Map Viewer?

**Comment by freddiesia** [comment]
I am able to add as a feature service and view the data in map viewer. However, when I used the Zoom To function, it failed to zoom in. Do you have this problem?

**Comment by jmp601** [comment]
Have you all tried to throw any custom parameters the service at it when adding a layer? I have noticed this is a requirement for certain feature services in the new viewer. https://developers.arcgis.com/web-map-specification/objects/customParameters/

**Comment by rgwozdz** [comment]
@AvidDabbler - wondering if we can close this?  Is it still an issue?

**Comment by AvidDabbler** [comment]
I think I got it to work. It been a while since I touched it but I think i finally got it to work.

**Comment by freddiesia** [comment]
Yes, you can close it now. Thanks.

**Comment by hildermesmedeiros** [comment]
> [@AvidDabbler](https://github.com/AvidDabbler) - seems to work fine in the current version of the map viewer:
> 
> * https://www.arcgis.com/apps/mapviewer/index.html?url=https://scoop.iotrans.it/vehicles/FeatureServer/
> * https://www.arcgis.com/apps/mapviewer/index.html?url=https://scoop.iotrans.it/stops_otp/FeatureServer/

It is not working anymore. I'm trying to integrate Koop with weather APIs. It works on ArcGIS Pro and other JavaScript apps, but it does not work in the web map.
