### ISSUE TITLE
Using Koop FeatureServer to render unique values in map through ArcGis JS API

### ISSUE THREAD

**Issue by biswaranjannaik** [koopjs/koop#382]
Hi Team,
              We are trying to render unique values based on datasets on Map component provided by react-arcgis, using the Koop FeatureServer. The renderer configured in the search indices is as follows:
  ```
  "renderer": {
		"type": "uniqueValue",
		"field": "FacilityField",
		"legendOptions": {
			"title": "Data Status"
		},
		"defaultSymbol": {
			"type": "esriSFS"
		},
		"uniqueValueInfos": [{
			"value": "Active",
			"symbol": {
				"type": "esriSFS"
			}
		}, {
			"value": "Planned",
			"symbol": {
				"type": "esriSFS"
			}
		}]
	}
```
We are able to populate legends on the map for the datasets as received from response. However, we aren't able to visualize any data points on the map. 

Following are our project configurations:
"koop": "^4.0.5",
"elasticsearch": "^14.2.0",
 "@elastic/elasticsearch": "^7.13.0"
 
 React: ^16.12.0
 ArcGis JS API: 4.13
  
Any help in resolving the above issue will be highly appreciated.

**Comment by OliviaMeowth** [comment]
Error in console: [esri.core.accessorSupport.extensions.serializableProperty.reader] Type 'unique-value' is not supported

**Comment by bsvensson** [comment]
@biswaranjannaik  @OliviaMeowth - do you get the same error with more recent versions of ArcGIS JSAPI? Current version is 4.22.

**Comment by biswaranjannaik** [comment]
We were able to fix this issue by changing the `field` attribute to `field1` instead as mentioned [here](https://developers.arcgis.com/web-map-specification/objects/uniqueValueRenderer/). 

Cheers!
@OliviaMeowth @bsvensson
