### ISSUE TITLE
Missing file(s) in winnow release

### ISSUE THREAD

**Issue by schmidtk** [koopjs/koop#449]
The released `winnow` package is missing `src/filter-and-transform/helpers/hash-fixture.json`, causing errors when `hash-function.js` is loaded. I believe this would be fixed by adding `src/**/*.json` to `files` in `winnow/package.json`, but I did not comb through to see if other files might be missing or if this would add unwanted files. Another solution would be refactoring to `hash-fixture.js` and exporting the fixture from a module.

Please advise on the preferred solution here, I would be happy to open a PR with the change. Thank you!

**Comment by rgwozdz** [comment]
Thanks @schmidtk, looking into it.

**Comment by rgwozdz** [comment]
Just released a fix.  koop-core 7.0.1, and it's downstream dependencies.

**Comment by schmidtk** [comment]
Thanks @rgwozdz!
