### ISSUE TITLE
Invalid regular expression error when query f=geojson

### ISSUE THREAD

**Issue by despainm** [koopjs/koop#469]
A string field that has a value that begins with the open parenthesis character `(` causes an error when the response format is geojson.

Example attribute value: `(my string)`

Error:
```
Invalid regular expression: /^(?!0{4}(0{2}(0{2})((?=[0-9]{4}((((0[^2])|1[0-2])|02(?=((([0-1][0-9])|2[0-8])))([0-9]{2})|(?=((([13579][26])|([2468][048])|(0[48]))0{2})|([0-9]{2}((((0|[2468])[48])|[2468][048])|([13579][26])))(02(29))([0-9]{4})((?!((0[469])|11)(31)((0[1,3-9]|1[0-2])|(02(?!(3)))((0[1-9]|[1-2][0-9]|3[0-1])$/: Unterminated group
```
The error is caused by `isValidISODateString(value)`
https://github.com/koopjs/koop/blob/49fe8407a1865cd532bc07d509939ac8c790696b/packages/featureserver/src/helpers/data-type-utils.js#L20

The root cause of the error is in the iso-datestring-validator package -> [isValidISODateString](https://github.com/Bwca/package_iso-datestring-validator/blob/5d9ffebc796184a9cd99105f7e4fae42d709068c/src/is-valid-iso-datestring/is-valid-iso-datestring.function.ts#L9) -> [getStringSeparator](https://github.com/Bwca/package_iso-datestring-validator/blob/5d9ffebc796184a9cd99105f7e4fae42d709068c/src/get-string-separator/get-string-separator.function.ts#L2).  When the provided string begins with `(` char the getStringSeparator returns `(` as the separator character which is provided to [isValidDate](https://github.com/Bwca/package_iso-datestring-validator/blob/5d9ffebc796184a9cd99105f7e4fae42d709068c/src/is-valid-date/is-valid-date.function.ts#L7) where the invalid regular expression error is triggered.

Can the [data-type-utils.js](https://github.com/koopjs/koop/blob/49fe8407a1865cd532bc07d509939ac8c790696b/packages/featureserver/src/helpers/data-type-utils.js#L19) check for the case when the string starts with `(` and assume that the string is not a date?

I've also requested a fix to the [iso-datestring-validator project](https://github.com/Bwca/package_iso-datestring-validator/issues/32#issuecomment-1442528601)

**Comment by rgwozdz** [comment]
Hey @despainm!  Thank you for reaching out.  I'm sure we can work something out.  Can you provide a sample Koop request that triggers this error?

**Comment by despainm** [comment]
`/arcgis/rest/services/<folder>/<serviceName>/FeatureServer/<layerId>/query?f=geojson`

In order to trigger the error the layer must contain an String attribute with a value that starts with an open parenthesis char `(`

**Comment by rgwozdz** [comment]
Ok, I follow now.  Thanks! Will pick this up soon.

**Comment by rgwozdz** [comment]
> Can the [data-type-utils.js](https://github.com/koopjs/koop/blob/49fe8407a1865cd532bc07d509939ac8c790696b/packages/featureserver/src/helpers/data-type-utils.js#L19) check for the case when the string starts with ( and assume that the string is not a date?

That seems reasonable.  Can you submit a PR?

**Comment by rgwozdz** [comment]
> That seems reasonable. Can you submit a PR?

@despainm, nevermind, I have something cooking.

**Comment by despainm** [comment]
You may be able to pull this change in once it is released https://github.com/Bwca/package_iso-datestring-validator/pull/35

**Comment by rgwozdz** [comment]
@despainm [@koopjs/koop-core@8.0.2](https://github.com/koopjs/koop/releases/tag/%40koopjs%2Fkoop-core%408.0.2) will give you the fix.

**Comment by despainm** [comment]
Fantastic!  Thanks for the quick response.
