### ISSUE TITLE
Possibiblity to overwrite default maxRecordCount of 2000 for output-geoservices

### ISSUE THREAD

**Issue by Kiachma** [koopjs/koop#511]
Hi,

I'd  like to override the maxRecordCount of my geoservices output, but I'm unable to find any documentation describing this.
It seems like https://github.com/koopjs/koop/blob/abb887489a5ab07d5d1ced7187bb5b0637d83640/packages/output-geoservices/src/index.js#L87 doesn't take into account metadata, so I'm not able to override it from the config file.

Is there any other way to handle this?

**Comment by rgwozdz** [comment]
Inactive, closing.
