### ISSUE TITLE
Support for PBF output from the built-in feature server output.

### ISSUE THREAD

**Issue by rgwozdz** [koopjs/koop#547]
Please add support for PBF output from the built-in feature server output.

_Originally posted by @jmburns in https://github.com/koopjs/koop/issues/529#issuecomment-1498912257_

**Comment by rgwozdz** [comment]
Thanks @jmburns.  It's definitely under consideration and high on the priority list.

**Comment by devilsgeographer** [comment]
This would be amazing!  geojson is not nearly as performant as PBF when loading features into the esri JS API.

**Comment by jmburns** [comment]
@rgwozdz has there been any progress on this?

**Comment by rgwozdz** [comment]
@jmburns - nothing yet, but Hacktober is coming, so maybe someone will pick it up.

**Comment by rgwozdz** [comment]
FYI, this is in-progress.

**Comment by rgwozdz** [comment]
https://github.com/koopjs/koop/pull/898

**Comment by jmburns** [comment]
Thanks @rgwozdz!
