### ISSUE TITLE
featureserver render-precalculated-statistics error when attribute value starts with open parenthesis

### ISSUE THREAD

**Issue by despainm** [koopjs/koop#589]
The render-precalculated-statistics.js [isDate](https://github.com/koopjs/koop/blob/6c9f0fa3a33768dd84e00736826401d5900e6d88/packages/featureserver/src/query/render-precalculated-statistics.js#L42) causes an `Invalid regular expression` error if the value being checked starts with an open parenthesis character `(`. 

This is the same error found in https://github.com/koopjs/koop/issues/469 and fixed by #470

**Comment by rgwozdz** [comment]
Thanks @despainm

**Comment by rgwozdz** [comment]
Should be fixed in [@koopjs/koop-core@8.0.8](https://github.com/koopjs/koop/releases/tag/%40koopjs%2Fkoop-core%408.0.8)
