### ISSUE TITLE
flesh out statistics support 

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#6]
set supportStats to true and return stats on requests with outStatistics defined (also accepts post reqs for stat calls...)

**Comment by Joshuaweg** [comment]
where do you set supportStats to true?

**Comment by rgwozdz** [comment]
Hi @Joshuaweg - this is a very old thread.  Current Koop supports the `outStatistics` query parameter without any additional configuration. See the [ArcGIS REST API docs on `outStatistics`](https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm) for details.  But here is an example:
`http://localhost:8080/github/koopjs::geodata::north-america/FeatureServer/0/query?outStatistics=[
  {
    "statisticType": "sum",
    "onStatisticField": "pop_est",
    "outStatisticFieldName": "Sum Pop"
  }]`
