### ISSUE TITLE
Feature tile requests for polyline and not point

### ISSUE THREAD

**Issue by bmoregeo** [koopjs/koop#676]
Hello, another esri js sdk interaction issue.

When I load a point layer from Koop into a feature layer in arcgis js sdk, it does the following request sequence:

1. .../query?f=json
2. .../query?resultRecordCount=true
3. .../query?limit=2000&offset=0
       [pages through till count from step two is hit]

When I load a polyline layer from Koop into a feature layer in arcgis js sdk, it does the following request sequence:
1. .../query?f=json
2. .../query?f=geometry={'xmin': xxx, 'ymin': xxx etc} 
        [pages through each tile in the map view and updates as panning around]

When dealing with large datasets, option one is problematic as it needs to have a count inorder to page through the expected results. Option two is better for my use case

I'm trying to figure out what about the koop response is telling ags js sdk to do the pagination in totally different ways (spatial vs tabular).

**Comment by rgwozdz** [comment]
@bmoregeo, thank you for posting this. Same as other issue, have you confirmed that this doesn't occur with the same data being served by a genuine ArcGIS Server (like a ArcGIS online service)?

**Comment by bmoregeo** [comment]
OK yeah. I guess this is just how the JS SDK works. super strange
