### ISSUE TITLE
Koop FeatureServices are not analyzable in ArcGIS Online

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#71]
FeatureServer endpoints are currently not able to be "analyzed" in ArcGIS online. My thoughts are that this has something to do with the Fields causing something in ArcGIS space to fail.

**Comment by pholleran** [comment]
@chelm - I have had mixed results with this. 
* I was able to use the buffer tool against: http://koop.dc.esri.com/socrata/detroitmi/encd-2smf/featureserver/0
* I was able to generate a hot spot analysis against: http://koop.dc.esri.com/socrata/detroitmi/vxm7-i6zf/featureServer/0
* BUT, I was not able to generate a hot spot analysis against: http://koop.dc.esri.com/socrata/detroitmi/stpb-gint!site_location/featureserver/0/query. ArcGIS Online returned the following error:

> Accessing url http://koop.dc.esri.com/socrata/detroitmi/stpb-gint!site_location/featureserver/0/query returned error The value type is incompatible with the field type. [site_location] Find Hot Spots failed.

**Comment by dmfenton** [comment]
Interesting. Site_location is an object. Perhaps flattening out all the fields will solve this.

**Comment by astauffer** [comment]
I thought we fixed this a while back. Was something with the fill symbol.

**Comment by pholleran** [comment]
Looks like it is just the multiple location column cases that are still causing an issue. I'll go back and take a look at how I handled those.

I added the use case to this issue since it was still open.

**Comment by ngoldman** [comment]
@pholleran is this still an issue? cc @jgravois

**Comment by dmfenton** [comment]
Feature Services work well in AGOL
