### ISSUE TITLE
Idea: Auto-generate dataset descriptions for FeatureServer endpoint

### ISSUE THREAD

**Issue by slibby** [koopjs/koop#88]
In the JSON returned for the /FeatureServer and /FeatureServer/0 requests, it would be nice to programatically generate some Dataset Description text that says:
- where the data came from
- what the layer is called
- that it is generated with "the X Provider" for Koop"
- some other metadata that could be configured in the provider

rather than `"serviceDescription":""`

This would improve the experience of users loading the layer to ArcGIS Online, creating a map from it, etc.

**Comment by dmfenton** [comment]
I added this in FeatureServer
