### ISSUE TITLE
Error with /rest/services/FeatureServer endpoint

### ISSUE THREAD

**Issue by cwalker-qp** [koopjs/koop#880]
Background:
I have successfully cloned and deployed the koop-app-sample repository as a docker container running in Azure.  The built-in providers, github and craigslist, both work as expected.  Mainly I have tested two specific endpoints that are relevant to my project-specific goals:

/github/koopjs::geodata::north-america/FeatureServer/0/query
/github/koopjs::geodata::north-america/FeatureServer

Both of the above endpoints work as expected.

I have also successfully added the built-in services as feature layers in ArcGIS Portal by pasting this URL:

https://<azure-app-service-url>/github/koopjs::geodata::north-america/FeatureServer

When I click New Item and paste the URL, Portal automatically senses that the URL is a valid Geoservice and the rest of the online wizard goes smoothly.  This however does not work with the custom provider I've developed.  Details below.

Goal - connect Koop to CosmosDB
I followed the docs to develop a new custom provider/plugin for pulling data from CosmosDB and added it into the sample project.  I placed the custom provider in /src/proivders/cosmosdb.

![koop-01](https://github.com/koopjs/koop-provider-github/assets/111528084/492fb4a1-5622-4de0-91a9-3ad5888c430a)

My getData function in model.js

```
Model.prototype.getData = async function (req, callback) {
  // console.log('request received:');
  // console.log(req.url);
  // console.log(req.body);
 
  // query options:
  const urlQueryString = req.url.split('?').slice(1).join('?');
  // console.log(urlQueryString);

  urlQueryParams = urlQueryString.split('&');
  // console.log(urlQueryParams);

  cosmosQueryOptions = {
    where: null,
    fields: []
  }

  try{
    if ('where' in req.body) {
      cosmosQueryOptions.where = req.body.where;

      crosshairsFieldNames.forEach(n => {
        cosmosQueryOptions.where = cosmosQueryOptions.where.replace(n, `c.${n}`);
      }); 
    }
  } catch (ex) {
    callback(ex, null);
  }

  try{
    const articles = await queryCosmos(cosmosQueryOptions);

    if (articles.length) {
      const geojson = translate(articles);

      // Add metadata
      geojson.metadata = geojson.metadata || {};
      geojson.title = `CosmosDB Crosshairs Articles`;
      geojson.metadata.geometryType = _.get(geojson, 'features[0].geometry.type');

      callback(null, geojson);
    }
  } catch (ex) {
    callback(ex, null);
  }
}
```

Running the app locally, the CosmosDB provider works as expected at the /cosmosdb/rest/services/FeatureServer/0/query endpoint.  It returns data in 1-3 seconds.  The data  I'm happy with this performance.

The Problem occurs when I try to add the service as a new item in ArcGIS Portal.  Portal's online wizard shows an error message but there are no details on what was wrong.

I began comparing my custom provider with the github provider that's built-in.  One key difference I notice is that the following endpoint works with the built-in github provider:

/github/koopjs::geodata::north-america/FeatureServer

The above URL returns the service's properties as you might expect:

```
{
    "serviceDescription": "",
    "hasVersionedData": false,
    "supportsDisconnectedEditing": false,
    "supportedQueryFormats": "JSON",
    "maxRecordCount": 2000,
    "hasStaticData": false,
    "capabilities": "Query",
    "description": "This is a feature service exposed with Koop, an open source project that turns APIs into features. Service Description information may not be available for all services. For more information, check out https://github.com/koopjs/koop",
    "copyrightText": "Copyright information varies from provider to provider, for more information please contact the source of this data",
    "spatialReference": {
        "wkid": 4326,
        "latestWkid": 4326
    },
    "initialExtent": {
        "xmin": -171.7911106028912,
        "ymin": 14.538828640190957,
        "xmax": -12.20855,
        "ymax": 83.64513,
        "spatialReference": {
            "wkid": 4326,
            "latestWkid": 4326
        }
    },
    "fullExtent": {
        "xmin": -171.7911106028912,
        "ymin": 14.538828640190957,
        "xmax": -12.20855,
        "ymax": 83.64513,
        "spatialReference": {
            "wkid": 4326,
            "latestWkid": 4326
        }
    },
    "allowGeometryUpdates": false,
    "units": "esriDecimalDegrees",
    "syncEnabled": false,
    "layers": [
        {
            "id": 0,
            "name": "north-america",
            "parentLayerId": -1,
            "defaultVisibility": true,
            "subLayerIds": null,
            "minScale": 0,
            "maxScale": 0,
            "geometryType": "esriGeometryPolygon"
        }
    ],
    "tables": [],
    "currentVersion": 10.51,
    "fullVersion": "10.5.1"
}
```

But the equivalent endpoint does not work with my custom provider.

https://<azure-app-service-url>/cosmosdb/rest/services/FeatureServer

The above URL returns this response:

```
{
    "error": "invalid extent passed in metadata"
}
```

I'm going on the assumption that this may be why I cannot add this service in Portal.  Instead of getting a response JSON object with valid service properties it gets the error shown above.

Where/how should I go about defining the provider's service properties?  Does Koop infer these properties automatically or must I define them manually?  I looked through the docs but couldn't find info on this specific issue.

Thanks for your help!

**Comment by rgwozdz** [comment]
@cwalker-qp - thanks for reaching out, and glad to hear you are using Koop.  It looks like the koop-app-example is pretty far behind the latest Koop version.  So before we dive to deep in we should update your app so that it is using the latest.  The npm has changed, so it not just a matter of bumping the version.

I will update this repository so you can see the changes. But here are the general step for what you need to do:

1. remove old Koop module: `npm uninstall koop`
2. add new Koop module: `npm install @koopjs/koop-core`
3. change the require statement so that the new module is used. So [this line](https://github.com/koopjs/koop-app-example/blob/master/src/index.js#L2C1-L2C29) needs to be changed to:

```js
const Koop = require('@koopjs/koop-core');
```
Give this a try and see if you get the expected results.  I will report back to this thread when the app-example is updated.

**Comment by rgwozdz** [comment]
koop-app-example has been updated.

**Comment by cwalker-qp** [comment]
Rich,

Thank you for your help!  I have made the changes you suggested.  In my project based on koop-app-example, I am now running @koopjs/koop-core instead of koop.

package.json
```
{
  "name": "koop-app-example",
  "description": "Sample koop express application with some common koop providers.",
  "version": "0.1.0",
  "author": "Esri R&D",
  "bugs": {
    "url": "https://github.com/koopjs/koop-app-example/issues"
  },
  "dependencies": {
    "@koopjs/koop-core": "^10.1.0",
    "@koopjs/provider-github": "^3.0.0",
    "config": "^3.2.5",
    "koop-provider-craigslist": "^2.0.1"
  },
  "devDependencies": {
    "@koopjs/cli": "^0.6.0",
    "standard": "^14.3.1",
    "tap-spec": "^5.0.0",
    "tape": "^5.0.0"
  },
  "homepage": "https://github.com/koopjs/koop-app-example",
  "keywords": [
    "agol",
    "arcgis",
    "etl",
    "example",
    "geojson",
    "gis",
    "gist",
    "github",
    "heroku",
    "koop",
    "postgres",
    "sample",
    "socrata"
  ],
  "license": "Apache-2.0",
  "main": "src/index.js",
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://github.com:koopjs/koop-app-example.git"
  },
  "scripts": {
    "start": "node src/index.js",
    "start:dev": "koop serve --save --watch",
    "test": "standard && tape test/*.js | tap-spec"
  }
}
```

src/index.js
```
const config = require('config')
const Koop = require('@koopjs/koop-core');
const routes = require('./routes')
const plugins = require('./plugins')

// initiate a koop app
const koop = new Koop()

// register koop plugins
plugins.forEach((plugin) => {
  koop.register(plugin.instance, plugin.options)
})

// add additional routes
routes.forEach((route) => {
  route.methods.forEach((method) => {
    koop.server[method](route.path, route.handler)
  })
})

// start the server
koop.server.listen(config.port, () => koop.log.info(`Koop server listening at ${config.port}`))
```

I noticed that my custom provider, which is based on koop-provider-sample, was also running koop instead of koop-core.  It has it's own package.json file.  Not sure if this matters, but I updated it as well.

/src/providers/cosmosdb/package.json
```
{
  "name": "koop-provider-sample",
  "version": "1.0.0",
  "description": "A sample provider for koop",
  "main": "src/index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "start": "koop serve",
    "test": "standard && tape test/*.js | tap-spec"
  },
  "dependencies": {
    "@azure/cosmos": "^4.0.0",
    "@koopjs/koop-core": "^10.1.0",
    "config": "^3.2.5",
    "request": "^2.88.0"
  },
  "author": "Daniel Fenton",
  "license": "Apache-2.0",
  "devDependencies": {
    "@koopjs/cli": "^0.6.0",
    "nock": "^12.0.0",
    "standard": "^14.3.1",
    "tap-spec": "^5.0.0",
    "tape": "^5.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/koopjs/koop-provider-sample.git"
  },
  "bugs": {
    "url": "https://github.com/koopjs/koop-provider-sample/issues"
  },
  "homepage": "https://github.com/koopjs/koop-provider-sample",
  "keywords": [
    "koop",
    "provider",
    "sample"
  ]
}
```

After making these changes I rebuilt the docker image and deployed it to Azure, running as an app service.  The URLs included below are live and will allow you to see the same responses I'm seeing.

The good news is that I am now getting an error-free response with correctly formatted JSON metadata at this endpoint:
https://qp-koop.azurewebsites.net/cosmosdb/rest/services/FeatureServer

The bad news is that it takes over 3 minutes to get the response.

By comparison, the built-in github provider returns in less than 1 second:
https://qp-koop.azurewebsites.net/github/rest/services/koopjs::geodata::north-america/FeatureServer

At first I thought maybe a full fetch of the cosmos data is happening before it returns the metadata, maybe to calculate the full extent?  But, my provider isn't a full fetch situation, it's pass-through.  For example, if you run the query below, the WHERE value is being translated by my custom provider into a valid CosmosDB where clause.  This request also returns quickly, less than 3 seconds for me via Postman:

POST
https://qp-koop.azurewebsites.net/cosmosdb/rest/services/FeatureServer/0/query?f=json&returnGeometry=true&outFields=trans_title, article_text, primary_category, second_category

body is x-www-form-encoded
where = primary_category='Crime' AND second_category='Drug' and (lower(trans_title) like '%seize%' OR lower(article_text) like '%seize%')


I went ahead and retried adding this service as a new item in ArcGIS Portal.  With other services, when I paste the URL into the form it automatically detects that it's a valid Geoservice.  With my URL from the cosmosdb provider it doesn't.

![koop-portal-add-item-01](https://github.com/koopjs/koop/assets/111528084/c49d4761-555d-46e5-a49e-1ece03d837ab)

If I proceed anyway, setting the type to ArcGIS Server web service, give it a title and submit, I get this error message:
![koop-portal-add-item-02](https://github.com/koopjs/koop/assets/111528084/67dbe809-fc62-4614-8cb5-0ee28483a420)

Any ideas on what my custom provider might be missing?

Thanks again for your time and help, it is greatly appreciated!

**Comment by rgwozdz** [comment]
Hey @cwalker-qp, thanks for all the info and context.  I think I get what is going on here.  It's the particulars of trying to build a pass-through provider.  If your dataset is large, a pass-through provider is a great way to improve performance.  But Koop was sort of designed with full-fetch providers in mind (a majority of the use cases so far).  There's are a few things that a pass-through provider needs to handle in a special way.  

### Explanation for slow response on /FeatureServer and /FeatureServer/0 requests
When these requests are made, Koop still routes to your `getData` handler method, because it uses the data returned to dynamical build some of the fields in the response (e.g., `extent`, `fields`).  But on these type of requests there is _no_ `where` parameter.  So your `getData` method attempts to fetch all the data before passing it on to Koop in the callback, hence the long return time.

### Pass-through workaround
This can be avoided by looking at the request when it arrives at `getData` and checking to see if the path matches `/FeatureServer` or `/FeatureServer/[0-9]+` and if it does do some special handling.  You can skip fetching data all together if you can set `metadata.fields`, `metadata.geometryType`, and `metadata.extent` in your provider. The other workaround is to set `metadata.extent` to the whole world (or any defined area you like) and then simply fetch one record from your provider. Koop will use the one record to build `fields` and determine `geometryType`.

**Comment by cwalker-qp** [comment]
Rich, thanks for the detailed explanations.  I'm going to start by manually defining metadata.geometryType, metadata.fields, and metadata.extent.  I have a couple of follow-up questions about this:

Would the metadata.extent object be the same structure as JSON returned by ArcGIS REST?  Like this...
```
"fullExtent": {
        "spatialReference": {
            "wkid": 4326,
            "latestWkid": 4326
        },
        "xmin": -171.7911106028912,
        "xmax": -12.20855,
        "ymin": 14.538828640190957,
        "ymax": 83.64513
    },
```

Likewise, would metadata.fields be an array structured like ArcGIS REST JSON?
```
"fields": [
        {
            "name": "trans_title",
            "type": "esriFieldTypeString",
            "alias": "trans_title",
            "sqlType": "sqlTypeOther",
            "domain": null,
            "defaultValue": null,
            "length": 128
        },
        {
            "name": "article_text",
            "type": "esriFieldTypeString",
            "alias": "article_text",
            "sqlType": "sqlTypeOther",
            "domain": null,
            "defaultValue": null,
            "length": 128
        },
        {
            "name": "primary_category",
            "type": "esriFieldTypeString",
            "alias": "primary_category",
            "sqlType": "sqlTypeOther",
            "domain": null,
            "defaultValue": null,
            "length": 128
        },
        {
            "name": "second_category",
            "type": "esriFieldTypeString",
            "alias": "second_category",
            "sqlType": "sqlTypeOther",
            "domain": null,
            "defaultValue": null,
            "length": 128
        }
    ],
```

If there is another JSON structure for metadata that's part of the GeoJSON standard, I couldn't find it in [RFC 7946](https://tools.ietf.org/html/rfc7946).

**Comment by rgwozdz** [comment]
@cwalker-qp - good questions. `extent` can be set like the ArcGIS envelope object you note above.  `fields` can be much more simple than what you posted above.  There are details [here](https://koopjs.github.io/docs/development/provider/model#adding-provider-metadata-to-the-geojson), but you can do something like:

```js
fields: [
{
  name: 'species',
  type: 'String',
  length: 15
},
{
  name: 'weight',
  type: 'Double',
},
]
```

Just remember to nest these properties inside the `metadata` property on your geojson object.

**Comment by cwalker-qp** [comment]
@rgwozdz Thanks for the clarification.  I've made some progress:

1. The getData() method is now updated to only return the top 1 record if the request is for /FeatureServer.  I'll add support for /FeatureServer[0-9]+ later on.

2. geojson.metadata now has hardcoded extent for the whole earth.
```
const articles = await queryCosmos(cosmosQueryOptions);
    if (articles.length) {
      const geojson = translate(articles);

      // Add metadata
      geojson.metadata = {
        extent: {
          spatialReference: {
            wkid: 4326,
            latestWkid: 4326
          },
          xmin: -180,
          xmax: 180,
          ymin: -90,
          ymax: 90
        },
      };

      geojson.title = `CosmosDB Crosshairs Articles`;

      callback(null, geojson);
```
3. I'm letting Koop determine the values for metadata.geometryType and metadata.fields based on the one returned record.  This seems like the least invasive approach for now.

After making these changes and rebuilding/deploying the docker container, I'm getting a response to this URL is 4 seconds or less.
https://qp-koop.azurewebsites.net/cosmosdb/rest/services/FeatureServer

I did some logging to confirm that CosmosDB is correctly returning the TOP 1 record in this case and it is.  Everything is looking much better.

Unfortunately the error persists when I try to add this service to ArcGIS Portal.
![koop-portal-add-item-02](https://github.com/koopjs/koop/assets/111528084/42dea220-f372-4c52-8b1a-0b1b2c238e30)

What does work, is adding the built-in github provider.  In fact, when I past the URL below, the form automatically detects that it's an ArcGIS Server web service and populates the second field for me.
![koop-portal-add-item-03](https://github.com/koopjs/koop/assets/111528084/dbc53b53-d205-4924-a697-6d097a6e9296)

After clicking next, it has also auto-populated the second form with values pulled from the service endpoint (I assume).
![koop-portal-add-item-04](https://github.com/koopjs/koop/assets/111528084/3fbf24a8-5607-414c-8028-8ba065929a7b)

If I finish clicking through the wizard it successfully adds the github provider as a hosted feature layer in Portal.

The github provider has something my CosmosDB provider does not.  We are so close!  Ideas on what it could be?

Thank you so much for sticking with me on this journey.  I really appreciate your time and assistance!

**Comment by rgwozdz** [comment]
When adding a new item to ArcGIS Online, I always have these kind of errors unless I provide a URL with a layer index.  Try using the url:

https://qp-koop.azurewebsites.net/cosmosdb/rest/services/FeatureServer/0

and let me know what happens.

By the way, the url above is very slow to load, so I think maybe you are still doing a full fetch for the layer-info request...?

**Comment by cwalker-qp** [comment]
Ok I've added support for requests ending in /FeatureServer/#

It's rebuilt and redeployed to Azure.  I'm getting swift responses now:
https://qp-koop.azurewebsites.net/cosmosdb/rest/services/FeatureServer/0

Sadly no joy in Portal yet.  The online form still isn't automatically populating anything when I paste the above URL including the /0.  Completing all steps and submitting results in the same old error.

![image](https://github.com/koopjs/koop/assets/111528084/cf9c362f-df93-4b1e-a270-9b24253ab260)

There must still be something missing in the metadata.  Other ideas?

**Comment by cwalker-qp** [comment]
I got a little farther by calling the ArcGIS REST API /additem endpoint via Postman.  I believe this is exactly what the Portal behind the scenes but probably it's doing some checks first, and those are what's failing, so it never actually tries to add the item.  That's my theory.

Calling /additem with a payload for adding a Feature Service with URL, I get a success response:
```
{
    "folder": "",
    "id": "d10da4df677d4f6e9c8fd838b18de5d9",
    "success": true
}
```

In my content I see the hosted feature layer:
![image](https://github.com/koopjs/koop/assets/111528084/48637da5-f174-4b5d-8882-aa38a1e1a9ef)

In the new item's Overview page I see the sublayer with "Not Set" as the name (this is consistent with what I saw in the JSON responses earlier).
![image](https://github.com/koopjs/koop/assets/111528084/bcc2022b-35d5-41f8-8e6f-1f9a7a8d6b6a)

I thought this was going to be it, but the Data tab is where the next problem arises.  The good news is that it sees the schema and populates the table with field names, but the loading message spins for exactly one minute before displaying Data Error.
![image](https://github.com/koopjs/koop/assets/111528084/3a642b89-00f9-4365-8f72-3f4388bc50d6)
![image](https://github.com/koopjs/koop/assets/111528084/174c00a1-82b2-4d04-bef6-309a18cd0bf6)

Looking at the dev console's Network history, the page tried twice to get a count of records from the feature service.  Both requests were cancelled after 1 minute.
![image](https://github.com/koopjs/koop/assets/111528084/7ed4b423-9133-4de9-b5d7-09a1df9b6e44)

Closer look at the request params:
![image](https://github.com/koopjs/koop/assets/111528084/c2eb2c51-9911-40fa-a910-2a36714a15c0)

Does Koop support queries with returnIdsOnly=true and returnCountyOnly=true ?

**Comment by rgwozdz** [comment]
> I think I see what's happening here. Portal's count only request is trying to get a count of the entire dataset (where 1=1). I ran this same request manually and it took over 3 minutes and returned an incorrect count of 2000. Apparently Portal cancels after 1 minute. So I think I have to update my custom provider to conditionally fetch the accurate total record count from CosmosDB more efficiently if returnCountOnly=true is in the request params.

Yes, I think this is at least part of what is happening.  Something may have changed in Portal with the routine for adding new items; I had not seen it choking on a count query at that stage, prior to this.  But yes, with a large dataset and pass-through provider, you will want to handle the COUNT operation on the remote API if possible.  Otherwise it's going to attempt a full-fetch and do the count in memory.

Sorry, someone needs to document all the particulars of a pass-through provider, but we just haven't done it yet.  If you want to see an example of a complete pass-through provider (filters, pagination, etc passed on to remote) take a look at the [mongo-db provider](https://github.com/koopjs/koop-provider-mongo/blob/master/src/model.js#L39).

Let's keep this thread going if you have more questions or run into more issues.  It will help someone write the docs.

**Comment by cwalker-qp** [comment]
Another step forward.  My CosmosDB provider now handles /query requests with returnCountOnly=true by sending a valid SELECT COUNT statement to the database instead of fetching all records. 

That request now returns immediately and the Data tab in Portal is showing the correct number of records.
![image](https://github.com/koopjs/koop/assets/111528084/1245e28f-002b-4be9-a809-e46b5255ce7c)

Now it's hanging on the initial query to populate the table:
![image](https://github.com/koopjs/koop/assets/111528084/edff1a9c-68fe-46ec-ad52-f209a52b2c66)

Next step is to update the provider to handle /query requests that include the **resultOffset** and **resultRecordCount** parameters.

**Comment by cwalker-qp** [comment]
@rgwozdz, I think I'm one step away from a working solution on this.  One last issue remains and I'm hoping you can tell me how to configure Koop to get around it.

I've updated my provider to handle the request parameters **resultOffset** and **resultRecordCount**.  They now get converted into an OFFSET LIMIT clause and added to the SQL statement that queries the database.

The problem is that these values are being double applied.

Example:
SELECT * FROM articles c WHERE c.primary_category='Crime' OFFSET 10 LIMIT 10

If I query the database directly using the above statement I get items 11 through 20 as expected (skipping the first 10 items and returning the next 10).

If I query Koop server with resultOffset=10 and resultRecordCount=10, it builds the same query shown above before querying the database, 10 records are returned to Koop server, and then Koop returns 0 records in the response.  I think it's because the request params are being applied again to the result set in memory before returning the response.

To test this theory, I sent another request to Koop server with resultOffset=1 and resultRecordCount=10.  The database returned 10 records and as expected, Koop only returned 9.  I think it applies the resultOffset of 1 to the in-memory result and then tries to take the next 10, but there were only 10 to begin with and 1 has been skipped, so I get 9 in the response.

Is there a way to disable Koop's processing of resultOffset and resultRecordCount since I am already handling them?

**Comment by rgwozdz** [comment]
@cwalker-qp - the quick answer to your question is to add a `filtersApplied` property to your geojson.  See [here](https://koopjs.github.io/docs/development/provider/model#query-parameters).   But I do have a word of warning on passing pagination parameters on to your remote API.  You should only do this if you have passed both your `where` and `geometry` filters on to the remote DB as well. You have noted passing the `where`, but have you been able to pass `geometry` on to Cosmos as well?

Consider the case if you don't pass the geometry filter on to Cosmo, but you do pass a limit parameter.  A request arrives with a `geometry` filter (polygon) and a `resultRecordCount` (10), which means "return the first 10 points found within this polygon".  The geometry filter needs to be applied first, and only after it is can you apply the limit.  If it happens in the other order your first 10 points might not fall within the polygon at all.  In that case, having Koop apply the geometry filter after Cosmo does the limit will result in an empty feature array even if your dataset does include points that fall within the requested polygon.

**Comment by cwalker-qp** [comment]
@rgwozdz I am probably not handling the CosmosDB client correctly.  Thanks for bringing this up.  I'd made a mental note to ask about it and forgot.

I'm instantiating the CosmosDB client in the provider's model.js.  So perhaps it gets recreated per request?  I was thinking it would get reused but I'm no expert at node server apps.

If there's a way to make a singleton CosmosDB client in /src/index.js, then inject it into the provider, maybe that's what I need to be doing.  Could I attach it to plugin.options?

```
// register koop plugins
plugins.forEach((plugin) => {
  koop.register(plugin.instance, plugin.options)
})
```

**Comment by rgwozdz** [comment]
You could do it in the constructor of your provider Model.

```js
class Model {
  constructor(koopParams, options) {
    // set up Cosmo connection here
  }

  getData (req, callback) {
     // get stuff from Cosmos here
  }
}

```

**Comment by cwalker-qp** [comment]
@rgwozdz I know we are straying beyond the scope of Koop at this point.  I cannot thank you enough for sticking with this issue and all it's minutia.

In the code base I'm working with, the provider has a functional constructor rather than class based.  I added the CosmosDB client, so this is what I have now:
```
function Model (koop) {
  this.cosmosClient = new cosmos.CosmosClient(config.cosmosDb.connectionString);

  this.getData = async function (req, callback) {
    cosmosQueryOptions = {
      where: null,
      fields: [],
      returnTopRecordOnly: false,
      returnCountOnly: false
    }
  
    if ('where' in req.body) {
      try {
        cosmosQueryOptions.where = req.body.where;
  
        crosshairsFieldNames.forEach(n => {
          cosmosQueryOptions.where = cosmosQueryOptions.where.replace(n, `c.${n}`);
        }); 
      } catch (ex) {
        callback(ex, null);
      }
    }
  
    if ('returnCountOnly' in req.query) {
      try {
        cosmosQueryOptions.returnCountOnly =  (req.query.returnCountOnly === 'true');
  
        if (cosmosQueryOptions.returnCountOnly) {
          const result = await getArticlesCount(this.cosmosClient, cosmosQueryOptions);
          callback(null, result[0]);
        }
      } catch (ex) {
        callback(ex, null);
      }
    }
  
    try {
      const regex = new RegExp(/\/FeatureServer(\/[0-9]+)?$/gm); // ends with /FeatureServer or /FeatureServer/#
      const match = req._parsedUrl.pathname.match(regex);
  
      if (match) {
        cosmosQueryOptions.returnTopRecordOnly = true;
      }
    } catch (ex) {
      callback(ex, null);
    }
  
    if ('resultRecordCount' in req.query) {
      cosmosQueryOptions.limit = req.query.resultRecordCount;
    }
  
    if ('resultOffset' in req.query) {
      cosmosQueryOptions.offset = req.query.resultOffset;
    }
  
    try {
      const articles = await getArticles(this.cosmosClient, cosmosQueryOptions);
  
      const geojson = translate(articles);
  
        // Add metadata
        geojson.metadata = {
          extent: {
            spatialReference: {
              wkid: 4326,
              latestWkid: 4326
            },
            xmin: -180,
            xmax: 180,
            ymin: -90,
            ymax: 90
          },
        };
  
        geojson.filtersApplied = {
          resultRecordCount: false,
          resultOffset: false,
        }
  
        callback(null, geojson);
    } catch (ex) {
      callback(ex, null);
    }
  }
}
```


After re-deploying I'm not seeing a change in behavior when scrolling the Portal item's Data table.  This time I let it go longer and it seems everything is canceled by the client at 1 minute.
![image](https://github.com/koopjs/koop/assets/111528084/48910c0d-d9b3-4f3d-9165-a5a513f1350e)

The numbers in the requests don't really add up either.  It's requesting 50 each time but the offset is jumping by way more than that, like 400+ per request.  This seems to be oddities of the Portal item's Data page rather than anything to do with Koop.

I still have a long way to go with Koop but I couldn't have gotten this far developing the custom provider without the help you've provided.  THANK YOU!

**Comment by rgwozdz** [comment]
> In the code base I'm working with, the provider has a functional constructor rather than class based. I added the CosmosDB client, so this is what I have now:

You can easily switch it to class syntax if you like (recommended), but not necessary.  having your getData defined as an instance property rather than a prototype method is also a bit non-standard, but I guess should be fine.

I'm not sure what to make of the weird values for `resultOffset`, usually they are always a multiple of `resultRecordCount`.  Maybe you should try this in a different client (ArcGIS online Map Viewer, or ArcGIS Pro) and see if you get same behavior.

**Comment by rgwozdz** [comment]
Closing this, original error was related to provider development.
