### ISSUE TITLE
Make Koop act like an actual node module 

### ISSUE THREAD

**Issue by chelm** [koopjs/koop#96]
As per comments from @ngoldman Koop should be a module, hosted, versioned, and installed via npm. This will make koop a very simple wrapper that loads all the installed providers at start up time and exposes itself as an Express app/middleware. 

This way we never actually deploy "koop" as an app, but rather as a deployable app/server (a new repo) that pulls in what ever providers you want such as github, gist, socrata, etc.

**Comment by ngoldman** [comment]
@chelm++ sounds great! I'm traveling right now so won't be able to take a good look until January 8th. Will follow up then. Happy New Year!
