### ISSUE TITLE
Error code is overridden by provider model

### ISSUE THREAD

**Issue by mtrcn** [koopjs/koop#978]
Hello,

As you see in the following code, the error code is overridden by the model and it makes it impossible to pass other codes such as 403 to the output plugin. 

https://github.com/koopjs/koop/blob/5cb4c20a4cca049d5615b2e6e07c515bffb2318e/packages/core/src/data-provider/extend-model.js#L208

This line should be removed from here and allow the auth plugin developer to send other codes.

**Comment by rgwozdz** [comment]
Fixed in 10.4.5
