### ISSUE TITLE
OwningSystemUrl breaks ArcGIS Pro authentication

### ISSUE THREAD

**Issue by mtrcn** [koopjs/koop#979]
In the recent change, OwningSystemUrl was added to RestInfo but it comes with another problem, now ArcGIS Pro authentication is not working because it thinks the Feature Layer is federated by an ArcGIS Portal and subsequent requests to KoopJs is failing with 404 errors. 

https://github.com/koopjs/koop/blob/5cb4c20a4cca049d5615b2e6e07c515bffb2318e/packages/featureserver/src/rest-info-route-handler.js#L20

**Comment by rgwozdz** [comment]
@mtrcn - thanks for this.  We'll get it sorted out ASAP.

**Comment by rgwozdz** [comment]
@mtrcn - see https://github.com/koopjs/koop/pull/980

**Comment by mtrcn** [comment]
Thanks for the quick fix, it looks good to me, on the other hand, we keep getting the credentials dialogue in ArcGIS Pro when we are using KoopJS layers even though we checked the store credentials option, it might be related to ArcGIS Pro 3.2, do you have any idea on this?

**Comment by rgwozdz** [comment]
Ok, this is good to know.  It is only happening in Pro?  what happens if you add the service to a ArcGIS Online map app?

**Comment by mtrcn** [comment]
AOL and JS API works fine with it but ArcGIS Pro has the problem.

**Comment by rgwozdz** [comment]
Ok, I will open up as a separate issue.

**Comment by rgwozdz** [comment]
Fixed in 10.4.5.
